mui/base-ui

README.md

Adapting the README with what I found relevant for Base UI specifically. Will comment on some things in particular.

[docs] Update the README

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
docs/README.md
docs/data/base/components/accordion/accordion.md
docs/data/base/components/checkbox/checkbox.md
docs/data/base/components/drawer/drawer.md
docs/data/base/components/number-input/number-input.md
docs/data/base/components/pagination/pagination.md
docs/data/base/components/radio-group/radio-group.md
docs/data/base/components/rating/rating.md
docs/data/base/components/toggle-button-group/toggle-button-group.md
docs/data/base/components/tooltip/tooltip.md
docs/data/base/getting-started/overview/overview.md
docs/data/base/getting-started/support/support.md
docs/data/base/guides/next-js-app-router/next-js-app-router.md
examples/base-ui-cra-ts/README.md
examples/base-ui-cra/README.md
examples/base-ui-nextjs-tailwind-ts/README.md
examples/base-ui-vite-tailwind-ts/README.md
examples/base-ui-vite-tailwind/README.md
packages/mui-base/README.md
packages/mui-base/package.json

Replaced references to the Core repo throughout the codebase.

[core] Replace old repo references

---

CONTRIBUTING.md
docs/package.json

https://www.notion.so/mui-org/Ports-b113d0d4c76c4db9a0ef99c703d0084c

[core] Set docs port to 3005

---

.circleci/config.yml

Following https://github.com/mui/material-ui/pull/41657

[core] Fix dedupe check on CI

---

README.md

Corrected the badges in the README file.

[core] Correct the Readme file

---

pnpm-lock.yaml

A small issue occurred when merging the renovate PRs - simple patch update: `'@types/react-dom': 18.2.25`

[core] Fix lockfile

---

docs/package.json
pnpm-lock.yaml

Match https://github.com/mui/mui-toolpad/pull/3425

[core] Use the root dependency

---

docs/data/base/components/popper/PlacementPopper.js
docs/data/base/components/popper/PlacementPopper.tsx

It's no longer possible: https://react.dev/blog/2024/04/25/react-19-upgrade-guide#ref-cleanup-required

[popper][docs] Prepare React 19

---

package.json
pnpm-lock.yaml

See https://github.com/mui/mui-x/pull/13160

[code-infra] Remove raw-loader

---

.stylelintrc.js
package.json
stylelint.config.js

While I am at it (https://github.com/mui/material-ui/pull/42411), I might as well update the config here too.

[code-infra] Use shared .stylelintrc.js config

---

README.md

I'm using the "https://master--material-ui.netlify.app/static/..." URL for now so the changes become visible, but once a new version with the `master` branch changes comes out in the Material repo, I'll change it to "https://mui/com/static/..." instead.
Also pushing some slight formatting changes!
Preview:

[docs] Add the logo to the README

---

docs/data/base/getting-started/support/support.md

BaseUI -> Base_UI on /base-ui/getting-started/support/

[docs] Fix the X link

---

docs/pages/experiments/anchor-positioning.tsx
packages/mui-base/package.json
packages/mui-base/src/Tooltip/Positioner/useTooltipPositioner.ts
packages/mui-base/src/utils/useAnchorPositioning.ts
pnpm-lock.yaml

Playground: https://deploy-preview-461--base-ui.netlify.app/experiments/anchor-positioning/

[core] Add `useAnchorPositioning` Hook

---

SECURITY.md

https://github.com/mui/mui-x/pull/14128 made me think about this. It's early, but why not.

[docs] Prepare security table for once it has its first release

---

.eslintignore

I guess we don't need this anymore.

[core] Remove /.yarn

---

docs/app/(content)/components/[slug]/page.tsx
docs/app/(content)/getting-started/[slug]/page.tsx
docs/app/(content)/guides/[slug]/page.tsx
docs/src/components/EditPageGithubLink.tsx

See issue in https://app.ahrefs.com/site-audit/6984453/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2CcontentType%2Cdepth%2Credirect%2CincomingAllLinks&current=14-09-2024T115402&filterId=b3b75b6257a370fcf9f1f73befb5deb5&issueId=c64d8847-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating

[docs-infra] Fix double //

---

docs/public/_redirects

The UX is broken in https://master--base-ui.netlify.app/components/react-tabs/#links when opening those links in a new tab.
I'm creating this PR to illustrate what seems to be a great way to handle https://app.ahrefs.com/site-audit/6984453/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Cdepth%2Ccompliant%2CincomingAllLinks%2Corigin&current=14-09-2024T115402&filterId=91013c8aafad4fe1f7a0ad504eccad42&issueId=c64da643-d0f4-11e7-8ed1-001e67ed4656&sorting=-pageRating.

[docs] Avoid dead links in demos

---

packages/mui-base/src/Slider/Root/SliderRoot.test.tsx

Same as https://github.com/mui/material-ui/pull/43809.

[docs] Fix 301 to chromium

---

.circleci/config.yml

The test_types_next job tried to use pnpm before setting it up and failed.

[test] Fix the test_types_next CI job

---

README.md

The information in the README about the current state of the library was not clear (or even misleading).

[docs] Make the readme specific to @base_ui/react

---

docs/data/components/field/UnstyledFieldAsync.js
docs/data/components/field/UnstyledFieldAsync.tsx
docs/data/components/field/UnstyledFieldIntroduction/system/index.js
docs/data/components/field/UnstyledFieldIntroduction/system/index.tsx
docs/data/components/field/UnstyledFieldPassword.js
docs/data/components/field/UnstyledFieldPassword.tsx
docs/data/components/field/UnstyledFieldServerError.js
docs/data/components/field/UnstyledFieldServerError.tsx
docs/data/components/field/field.mdx
docs/data/components/form/FormIntroduction/system/index.js
docs/data/components/form/FormIntroduction/system/index.tsx
packages/mui-base/src/Field/Root/FieldRoot.test.tsx
packages/mui-base/src/Field/utils/constants.ts

[Field] Refactor `data-field` style hook to `data-valid`/`data-invalid`

---

docs/data/components/popover/popover.mdx
packages/mui-base/src/Menu/Positioner/useMenuPositioner.ts
packages/mui-base/src/Popover/Backdrop/usePopoverBackdrop.ts
packages/mui-base/src/Popover/Positioner/usePopoverPositioner.tsx
packages/mui-base/src/PreviewCard/Backdrop/usePreviewCardBackdrop.ts
packages/mui-base/src/PreviewCard/Positioner/usePreviewCardPositioner.ts
packages/mui-base/src/Tooltip/Positioner/useTooltipPositioner.ts

[core] Remove baked-in max z-index from popup components

---

docs/reference/generated/select-arrow.json
docs/reference/generated/select-backdrop.json
docs/reference/generated/select-group-label.json
docs/reference/generated/select-group.json
docs/reference/generated/select-icon.json
docs/reference/generated/select-option-indicator.json
docs/reference/generated/select-option-text.json
docs/reference/generated/select-option.json
docs/reference/generated/select-popup.json
docs/reference/generated/select-positioner.json
docs/reference/generated/select-root.json
docs/reference/generated/select-scroll-down-arrow.json
docs/reference/generated/select-scroll-up-arrow.json
docs/reference/generated/select-trigger.json
docs/reference/generated/select-value.json

As #818 was merged in without including changes from #541, we have broken CI checks. This PR fixes the issue by regenerating the API docs

[docs] Add missing API definition files for Select

---

docs/data/api/alert-dialog-root.json
docs/data/api/dialog-root.json
docs/data/api/menu-checkbox-item.json
docs/data/api/switch-root.json
docs/data/translations/api-docs/menu-checkbox-item/menu-checkbox-item.json
docs/data/translations/api-docs/switch-root/switch-root.json
docs/reference/generated/alert-dialog-root.json
docs/reference/generated/dialog-root.json
docs/reference/generated/menu-checkbox-item.json
docs/reference/generated/switch-root.json
packages/mui-base/src/AlertDialog/Root/AlertDialogRoot.tsx
packages/mui-base/src/Dialog/Root/DialogRoot.tsx
packages/mui-base/src/Dialog/Root/useDialogRoot.ts
packages/mui-base/src/Menu/CheckboxItem/MenuCheckboxItem.tsx
packages/mui-base/src/Switch/Root/SwitchRoot.tsx
packages/mui-base/src/Switch/Root/useSwitchRoot.ts

Added missing `@default` JSDocs tags to `default*` props.

[docs] Add default value annotations to JSDocs

---

docs/data/api/menu-positioner.json
docs/data/api/popover-positioner.json
docs/data/api/preview-card-positioner.json
docs/data/api/select-positioner.json
docs/data/api/tooltip-positioner.json
docs/reference/generated/menu-positioner.json
docs/reference/generated/popover-positioner.json
docs/reference/generated/preview-card-positioner.json
docs/reference/generated/select-positioner.json
docs/reference/generated/tooltip-positioner.json
packages/mui-base/src/Menu/Positioner/MenuPositioner.tsx
packages/mui-base/src/Menu/Positioner/useMenuPositioner.ts
packages/mui-base/src/Popover/Positioner/PopoverPositioner.tsx
packages/mui-base/src/Popover/Positioner/usePopoverPositioner.tsx
packages/mui-base/src/PreviewCard/Positioner/PreviewCardPositioner.tsx
packages/mui-base/src/PreviewCard/Positioner/usePreviewCardPositioner.ts
packages/mui-base/src/Select/Positioner/SelectPositioner.tsx
packages/mui-base/src/Select/Positioner/useSelectPositioner.ts
packages/mui-base/src/Tooltip/Positioner/TooltipPositioner.tsx
packages/mui-base/src/Tooltip/Positioner/useTooltipPositioner.ts
packages/mui-base/src/utils/useAnchorPositioning.ts

[core] Use clipping-ancestors casing for public API

---

renovate.json

https://github.com/mui/base-ui/pull/795#issuecomment-2488968890

[dependencies] Update Tailwind CSS packages together

---

.eslintrc.js
docs/src/components/AppBar.tsx
docs/vitest.config.mts
packages/react/vitest.config.mts

Start with downstream, before https://github.com/mui/material-ui/pull/44489 gets applied, to be sure the propagation can be smooth.

[core] Add no-relative-packages

---

docs/src/app/new/(content)/layout.css
docs/src/app/new/(content)/layout.tsx
docs/src/app/new/layout.css
docs/src/breakpoints.css
docs/src/components/Code.css
docs/src/components/Code.tsx
docs/src/components/GhostButton.css
docs/src/components/Popup.css
docs/src/components/Popup.tsx
docs/src/components/Select.css
docs/src/components/Select.tsx
docs/src/components/SideNav.tsx
docs/src/components/Table.css
docs/src/components/Table.tsx
docs/src/components/reference/AttributesTable.tsx
docs/src/components/reference/CssVariablesTable.tsx
docs/src/components/reference/PropsTable.tsx
docs/src/components/reference/ReferenceTablePopover.tsx
docs/src/fonts/index.css
docs/src/mdx-components.tsx

https://deploy-preview-866--base-ui.netlify.app/new/components/dialog

[docs] Mobile layout

---

packages/react/src/Composite/Root/useCompositeRoot.ts

Part of https://github.com/mui/base-ui/issues/831

[Composite] Detect text direction in event handler instead

---

docs/src/components/Select.css

[docs] Fix select arrow alignment

---

docs/scripts/reportBrokenLinks.mts

Fixes the TS check in CI, it didn't pass when https://github.com/mui/base-ui/pull/903 was merged

[core] Fix TS error in reportBrokenLinks script

---

packages/react/src/utils/popupStateMapping.ts

[popups] Add `data-closed` style hook

---

docs/src/styles.css

[docs] Fix unexpected red text

---

docs/src/app/(public)/(content)/react/components/tabs/demos/hero/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/tabs/demos/hero/tailwind/index.tsx

Closes https://github.com/mui/base-ui/issues/1035

[docs] Add focus styles to the tabs demo

---

packages/react/src/accordion/header/AccordionHeader.test.tsx
packages/react/src/accordion/panel/AccordionPanel.test.tsx
packages/react/src/accordion/trigger/AccordionTrigger.test.tsx
packages/react/src/collapsible/panel/CollapsiblePanel.test.tsx
packages/react/src/collapsible/root/CollapsibleRoot.tsx
packages/react/src/collapsible/trigger/CollapsibleTrigger.test.tsx
packages/react/src/utils/collapsibleOpenStateMapping.ts

Matches the change in https://github.com/mui/base-ui/pull/1013/files

[Collapsible] Update `data-closed` attr

---

docs/src/app/(public)/(content)/react/components/slider/demos/hero/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/slider/demos/hero/tailwind/index.tsx

Follow up to https://github.com/mui/base-ui/pull/1017, https://github.com/mui/base-ui/issues/981

[docs] Remove position property from Slider demos

---

docs/src/app/(public)/(content)/react/components/accordion/demos/hero/css-modules/index.tsx
docs/src/app/(public)/(content)/react/components/checkbox/demos/hero/css-modules/index.tsx

In https://github.com/mui/base-ui/pull/1042 I accidently merged some demo changes that I did while testing locally. This PR reverts the changes.

[docs] Revert unintended demo changes

---

packages/react/src/radio-group/RadioGroup.test.tsx
packages/react/src/radio/root/useRadioRoot.tsx
packages/react/src/toggle-group/ToggleGroup.test.tsx
packages/react/src/toggle/Toggle.test.tsx
packages/react/src/toggle/Toggle.tsx

Closes https://github.com/mui/base-ui/issues/1084

[Radio][Toggle] Set both `disabled` and `data-disabled`

---

packages/react/src/field/root/FieldRoot.test.tsx
packages/react/src/number-field/root/useNumberFieldRoot.ts

[NumberField] Check for Field disabled state

---

packages/react/src/number-field/decrement/NumberFieldDecrement.test.tsx
packages/react/src/number-field/increment/NumberFieldIncrement.test.tsx
packages/react/src/number-field/root/useNumberFieldRoot.ts

[NumberField] Commit value upon increment/decrement

---

docs/reference/generated/menu-arrow.json
docs/reference/generated/menu-positioner.json
docs/reference/generated/popover-arrow.json
docs/reference/generated/popover-positioner.json
docs/reference/generated/preview-card-arrow.json
docs/reference/generated/preview-card-positioner.json
docs/reference/generated/select-arrow.json
docs/reference/generated/select-positioner.json
packages/react/src/menu/arrow/MenuArrowDataAttributes.ts
packages/react/src/menu/positioner/MenuPositionerDataAttributes.ts
packages/react/src/popover/arrow/PopoverArrowDataAttributes.ts
packages/react/src/popover/positioner/PopoverPositionerDataAttributes.ts
packages/react/src/preview-card/arrow/PreviewCardArrowDataAttributes.ts
packages/react/src/preview-card/positioner/PreviewCardPositionerDataAttributes.ts
packages/react/src/select/arrow/SelectArrowDataAttributes.ts
packages/react/src/select/positioner/SelectPositionerDataAttributes.ts

[docs] Fix arrow and positioner data attribute 

---

docs/next.config.mjs
docs/src/app/(public)/(content)/react/overview/accessibility/page.mdx
docs/src/components/Link.tsx
docs/src/components/kbd/Kbd.css
docs/src/components/kbd/Kbd.tsx
docs/src/components/kbd/rehype-kbd.mjs
docs/src/components/subtitle/rehypeSubtitle.mjs
docs/src/mdx-components.tsx
docs/src/styles.css

[docs] Style kbd

---

docs/src/blocks/sandbox/CreateReactApp.ts
docs/src/blocks/sandbox/packDemo.test.ts
docs/src/blocks/sandbox/packDemo.ts
docs/src/components/demo/CodeSandboxLink.tsx

- Fix dark theme with CodeSandbox
- Change the entry point name from Demo.tsx to App.tsx as a more idiomatic one

[docs] Fix CodeSandbox dark theme

---

docs/src/components/demo/Demo.css

Centering is broken on some demos, like Input

[docs] Fix demos centering

---

docs/next.config.mjs
docs/package.json
docs/src/styles.css
pnpm-lock.yaml

Automatically use curly quotes, em dashes, etc.

[docs] Automatic nice typography

---

docs/reference/generated/accordion-panel.json
docs/reference/generated/collapsible-panel.json
docs/reference/generated/dialog-popup.json
docs/reference/generated/menu-positioner.json
docs/reference/generated/popover-positioner.json
docs/reference/generated/preview-card-positioner.json
docs/reference/generated/scroll-area-root.json
docs/reference/generated/scroll-area-scrollbar.json
docs/reference/generated/select-positioner.json
docs/reference/generated/tabs-indicator.json
docs/reference/generated/tooltip-positioner.json
scripts/buildApiDocs/buildReference.ts

Fixed: https://deploy-preview-1131--base-ui.netlify.app/react/components/accordion#panel

[docs] Fix CSS vars generation

---

packages/react/src/utils/useScrollLock.ts

Partially addresses #1130. There are still some details to work out regarding small jumps

[useScrollLock] Handle Safari pinch-zooming

---

docs/src/app/(public)/(content)/react/components/menu/demos/checkbox-items/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/menu/demos/checkbox-items/css-modules/index.tsx
docs/src/app/(public)/(content)/react/components/menu/demos/checkbox-items/index.ts
docs/src/app/(public)/(content)/react/components/menu/demos/checkbox-items/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/menu/demos/group-labels/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/menu/demos/group-labels/css-modules/index.tsx
docs/src/app/(public)/(content)/react/components/menu/demos/group-labels/index.ts
docs/src/app/(public)/(content)/react/components/menu/demos/group-labels/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/menu/demos/open-on-hover/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/menu/demos/open-on-hover/css-modules/index.tsx
docs/src/app/(public)/(content)/react/components/menu/demos/open-on-hover/index.ts
docs/src/app/(public)/(content)/react/components/menu/demos/open-on-hover/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/menu/demos/radio-items/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/menu/demos/radio-items/css-modules/index.tsx
docs/src/app/(public)/(content)/react/components/menu/demos/radio-items/index.ts
docs/src/app/(public)/(content)/react/components/menu/demos/radio-items/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/menu/demos/submenu/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/menu/demos/submenu/css-modules/index.tsx
docs/src/app/(public)/(content)/react/components/menu/demos/submenu/index.ts
docs/src/app/(public)/(content)/react/components/menu/demos/submenu/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/menu/page.mdx
docs/src/components/Code.css
docs/src/components/CodeBlock.css
docs/src/components/CodeBlock.tsx
docs/src/components/demo/Demo.tsx
docs/src/components/demo/DemoSourceBrowser.tsx
docs/src/mdx-components.tsx
docs/src/styles.css
docs/src/syntax-highlighting/index.css

- Add code block line highlights
- Add menu checkbox items demo
- Note: check icon isn't unmounted yet, I'll create an issue
- Add menu open on hover demo
- Add menu with submenu demo

[docs] Add menu demos

---

docs/src/app/(public)/(content)/react/components/alert-dialog/page.mdx
docs/src/app/(public)/(content)/react/components/dialog/demos/close-confirmation/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/dialog/demos/close-confirmation/css-modules/index.tsx
docs/src/app/(public)/(content)/react/components/dialog/demos/close-confirmation/index.ts
docs/src/app/(public)/(content)/react/components/dialog/demos/close-confirmation/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/dialog/demos/nested/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/dialog/demos/nested/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/dialog/page.mdx

https://deploy-preview-1164--base-ui.netlify.app/react/components/dialog#close-confirmation

[docs] Add a confirmation dialog demo

---

docs/src/components/SideNav.css
docs/src/components/SideNav.tsx

[docs] Full width sidenav links

---

packages/react/src/progress/indicator/ProgressIndicator.test.tsx
packages/react/src/progress/indicator/useProgressIndicator.ts

Fixes https://github.com/mui/base-ui/issues/1203

[Progress] Set zero width when value is zero

---

docs/package.json

Equivalent of https://github.com/mui/mui-x/pull/15959
Already applied in Material UI https://github.com/mui/material-ui/pull/44823

[docs-infra] Remove Next.js production profiler

---

docs/src/components/Demo/DemoVariantSelector.tsx

Fix a11y violation reported by Lighthouse

[docs] Add accessible label to demo variant selector

---

docs/src/components/Demo/CodeSandboxLink.tsx

This link is now a redirection.
---
A side note: we will need to update the Tailwind CSS version use https://tailwindcss.com/docs/installation/play-cdn.

[core] Update to new Tailwind docs

---

docs/src/components/Demo/CodeSandboxLink.tsx

Before: https://codesandbox.io/p/sandbox/qd9rpz?file=%2Fpackage.json%3A9%2C3
After: https://codesandbox.io/p/sandbox/pcnt53?file=%2Fpackage.json%3A12%2C5

[docs] Update demo sandboxes to use React 19

---

CHANGELOG.md
docs/src/app/(public)/(content)/react/overview/releases/page.mdx
package.json
packages/react/package.json

[release] 1.0.0-alpha.6

---

scripts/README.md

A follow up to #1417 to fix https://github.com/mui/base-ui/pull/1417#discussion_r1954132533

[docs] Update the release instructions

---

scripts/buildTypes.mts

* Fix `copyDeclarations` as per https://github.com/mui/material-ui/pull/45422
* Also noticed a set of promises that weren't at all awaited for

[code-infra] Fix build:types not copying on some setups

---

docs/reference/generated/number-field-root.json
docs/reference/overrides/number-field-root.json
packages/react/src/number-field/root/NumberFieldRoot.test.tsx
packages/react/src/number-field/root/NumberFieldRoot.tsx
packages/react/src/number-field/root/useNumberFieldRoot.ts
packages/react/src/number-field/utils/parse.ts
packages/react/src/utils/formatNumber.ts

[NumberField] Add `locale` prop

---

packages/react/src/utils/useForkRef.test.tsx
packages/react/src/utils/useForkRef.ts

Fixes #1547
Ports [Floating UI's](https://github.com/floating-ui/floating-ui/pull/3222) new one over—all the existing tests pass. I added the new test as well.

[useForkRef] Support ref cleanup functions

---

docs/reference/generated/number-field-root.json
docs/reference/generated/number-field-scrub-area.json
docs/reference/generated/select-item-indicator.json
packages/react/src/number-field/root/NumberFieldRoot.tsx
packages/react/src/number-field/root/useNumberFieldRoot.ts
packages/react/src/number-field/scrub-area/NumberFieldScrubArea.tsx
packages/react/src/select/item-indicator/SelectItemIndicator.tsx
packages/react/src/select/popup/useSelectPopup.ts
packages/react/src/select/root/SelectRootContext.ts
packages/react/src/select/root/useSelectRoot.ts
packages/react/src/use-render/useRender.ts

Misc fixes I encountered working in other PRs

[core] Misc cleaning

---

packages/react/src/collapsible/panel/CollapsiblePanel.tsx

CollapsiblePanel will render a div.
https://github.com/mui/base-ui/blob/d389076a764f378550c711cff16057ffd58aebbb/packages/react/src/collapsible/panel/CollapsiblePanel.tsx#L14-L23

[Collapsible] Fix ForwardedRef type of CollapsiblePanel

---

packages/react/src/slider/indicator/useSliderIndicator.ts

Fixes #1480
Before: https://codesandbox.io/p/sandbox/peaceful-beaver-7t3dk5
After: https://codesandbox.io/p/sandbox/base-ui-cra-ts-forked-lzq4tl

[Slider] Fix incorrect CSS position on vertical slider indicator 

---

packages/react/src/checkbox/root/CheckboxRoot.test.tsx
packages/react/src/checkbox/root/useCheckboxRoot.ts
packages/react/src/radio-group/RadioGroup.test.tsx
packages/react/src/radio-group/useRadioGroup.ts
packages/react/src/select/root/SelectRoot.test.tsx
packages/react/src/select/root/useSelectRoot.ts
packages/react/src/slider/root/SliderRoot.test.tsx
packages/react/src/slider/root/SliderRoot.tsx
packages/react/src/switch/root/SwitchRoot.test.tsx
packages/react/src/switch/root/useSwitchRoot.ts

[form controls][Field] Fix forwarding of `name` and `disabled` props

---

docs/reference/generated/scroll-area-content.json
docs/src/app/(public)/(content)/react/components/scroll-area/demos/hero/css-modules/index.tsx
packages/react/src/scroll-area/content/ScrollAreaContent.test.tsx
packages/react/src/scroll-area/content/ScrollAreaContent.tsx
packages/react/src/scroll-area/index.parts.ts
packages/react/src/scroll-area/viewport/useScrollAreaViewport.tsx

[ScrollArea] `Content` part

---

docs/src/app/(public)/(content)/react/components/toolbar/demos/hero/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/toolbar/demos/hero/tailwind/index.tsx

[docs] Fix toolbar demo on small screens

---

packages/react/package.json
packages/react/src/tooltip/provider/TooltipProvider.test.tsx
packages/react/src/tooltip/provider/TooltipProvider.tsx
packages/react/src/tooltip/provider/TooltipProviderContext.ts
packages/react/src/tooltip/root/useTooltipRoot.ts
pnpm-lock.yaml

From https://github.com/floating-ui/floating-ui/pull/3274

[Tooltip] Avoid re-rendering unrelated consumers

---

.codesandbox/template/package.json
docs/package.json
packages/eslint-plugin-material-ui/package.json
scripts/api-docs-builder/package.json
test/node-resolution/package.json
test/package.json

Propagate https://github.com/mui/mui-x/pull/17582

[core] Remove unecessary versions

---

docs/reference/generated/input.json
packages/react/src/input/Input.tsx

Closes https://github.com/mui/base-ui/issues/1912

[input] Fix `Input.Props` type

---

docs/reference/generated/slider-root.json
docs/reference/generated/use-render.json
packages/react/src/slider/root/SliderRoot.tsx
packages/react/src/use-render/useRender.spec.tsx
packages/react/src/use-render/useRender.test.tsx
packages/react/src/use-render/useRender.ts
packages/react/src/utils/useRenderElement.spec.tsx
packages/react/src/utils/useRenderElement.tsx
pnpm-lock.yaml
scripts/api-docs-builder/package.json
scripts/api-docs-builder/src/componentHandler.ts
scripts/api-docs-builder/src/formatter.ts
scripts/api-docs-builder/src/hookHandler.ts
scripts/api-docs-builder/src/index.ts

Fixes https://github.com/mui/base-ui/pull/1967#issuecomment-2908795521

[useRender] Fix return type

---

docs/src/app/(public)/(content)/react/utils/use-render/page.mdx

Fixes https://github.com/mui/base-ui/pull/1988#issuecomment-2918589913

[docs] Fix issues in useRender docs

---

docs/src/app/(public)/(content)/react/utils/use-render/page.mdx

[docs] Fix additional issues in useRender docs

---

docs/reference/generated/select-value.json
docs/src/app/(private)/experiments/form.tsx
docs/src/app/(private)/experiments/long-select.tsx
docs/src/app/(private)/experiments/modality.tsx
docs/src/app/(private)/experiments/popups/popups-in-popups.tsx
docs/src/app/(private)/experiments/scroll-area/inside-select.tsx
docs/src/app/(private)/experiments/select-perf.tsx
docs/src/app/(private)/experiments/toolbar/text-editor.tsx
docs/src/app/(public)/(content)/react/components/select/demos/hero/css-modules/index.tsx
docs/src/app/(public)/(content)/react/components/select/demos/hero/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/toolbar/demos/hero/css-modules/index.tsx
docs/src/app/(public)/(content)/react/components/toolbar/demos/hero/tailwind/index.tsx
docs/src/app/(public)/(content)/react/handbook/animation/page.mdx
docs/src/components/Demo/DemoVariantSelector.tsx
docs/src/components/Experiments/Select.tsx
docs/src/components/Select.tsx
packages/react/src/select/item-indicator/SelectItemIndicator.test.tsx
packages/react/src/select/item/SelectItem.test.tsx
packages/react/src/select/root/SelectRoot.test.tsx
packages/react/src/select/trigger/SelectTrigger.test.tsx
packages/react/src/select/value/SelectValue.test.tsx
packages/react/src/select/value/SelectValue.tsx

Continuation of https://github.com/mui/base-ui/pull/1906#issuecomment-2897274740

[select] Revert `placeholder` API

---

docs/src/components/Header.tsx
docs/src/components/MobileNav.css
docs/src/components/MobileNav.tsx

Follow up to https://github.com/mui/base-ui/issues/1800

[docs] Add new badge to MobileNav

---

docs/reference/generated/navigation-menu-popup.json
docs/reference/generated/navigation-menu-positioner.json
docs/src/app/(public)/(content)/react/components/context-menu/page.mdx
docs/src/app/(public)/(content)/react/components/menubar/page.mdx
docs/src/app/(public)/(content)/react/components/navigation-menu/page.mdx
docs/src/app/(public)/(content)/react/utils/use-render/page.mdx
packages/react/package.json
packages/react/src/navigation-menu/popup/NavigationMenuPopupCssVars.ts
packages/react/src/navigation-menu/positioner/NavigationMenuPositionerCssVars.ts
pnpm-lock.yaml

- `@floating-ui/react@0.27.10` fixes a minor regression with menu submenus when the pointer is moved back into the parent popup and focuses an item (the submenu should close)

[docs] Fix misc errors

---

packages/react/src/avatar/fallback/AvatarFallback.tsx
packages/react/src/avatar/image/AvatarImage.tsx
packages/react/src/avatar/root/AvatarRoot.tsx

[avatar] Refactor to `useRenderElement`

---

packages/react/src/separator/Separator.tsx

[separator] Refactor to `useRenderElement`

---

packages/react/src/meter/indicator/MeterIndicator.tsx
packages/react/src/meter/label/MeterLabel.tsx
packages/react/src/meter/root/MeterRoot.tsx
packages/react/src/meter/track/MeterTrack.tsx
packages/react/src/meter/value/MeterValue.tsx

[meter] Refactor to `useRenderElement`

---

packages/react/src/menu/trigger/MenuTrigger.test.tsx

The PR had not sync'd with main yet which changed the test semantics

[test] Fix new `MenuTrigger` test

---

packages/react/src/menu/group/MenuGroupContext.ts
packages/react/src/select/root/SelectRootContext.ts
packages/react/src/toast/root/ToastRootContext.ts
packages/react/src/utils/useEventCallback.ts
packages/react/src/utils/useRenderElement.tsx

https://github.com/mui/base-ui/pull/1463/files#diff-44423f5dd8af8f593a150570e06df77e87fa579b9ba5879f10704df456e7e387 shows a couple of inconsistencies in our error messages.

[all components] Make error messages consistent

---

packages/react/src/menu/checkbox-item/MenuCheckboxItem.tsx
packages/react/src/menu/item/MenuItem.tsx
packages/react/src/menu/item/useMenuItem.ts
packages/react/src/menu/positioner/MenuPositioner.tsx
packages/react/src/menu/radio-item/MenuRadioItem.tsx
packages/react/src/menu/submenu-trigger/MenuSubmenuTrigger.tsx
packages/react/src/menu/trigger/MenuTrigger.tsx

Fixes #1947 
https://deploy-preview-2067--base-ui.netlify.app/experiments/menu/menu-fully-featured

[menu] Emit `close` event on `cancel-open`

---

packages/react/src/utils/floating-ui/useClick.ts
packages/react/src/utils/useRenderElement.tsx

[core] Fix object references

---

docs/src/app/(private)/experiments/menu/menu-fully-featured.tsx
packages/react/src/popover/trigger/PopoverTrigger.test.tsx
packages/react/src/utils/floating-ui/useClick.ts

[popups] Fix close toggle when rendering non-native button

---

docs/reference/generated/field-control.json
docs/reference/generated/input.json
packages/react/src/field/control/FieldControl.tsx

[field][input] Fix `onValueChange` `value` type

---

packages/react/src/composite/item/CompositeItem.tsx
packages/react/src/composite/root/CompositeRoot.test.tsx
packages/react/src/toggle-group/ToggleGroup.test.tsx
packages/react/src/toolbar/button/ToolbarButton.test.tsx
packages/react/src/toolbar/input/ToolbarInput.test.tsx
packages/react/src/toolbar/root/ToolbarRoot.test.tsx

[composite] Remove highlighted state

---

docs/reference/generated/navigation-menu-root.json
packages/react/src/navigation-menu/content/NavigationMenuContent.tsx
packages/react/src/navigation-menu/root/NavigationMenuRoot.tsx

[navigation menu] Fix typos

---

packages/react/src/tabs/tab/TabsTab.tsx

This wasn't in the `State` type to begin with, match #2109

[tabs] Remove highlighted state

---

packages/react/src/select/value/SelectValue.tsx

[select] Pass `value` as state

---

packages/react/src/select/trigger/SelectTrigger.tsx

[select] Extend `FieldRoot.State` type

---

docs/src/app/(public)/(content)/layout.css
docs/src/app/(public)/layout.css
docs/src/app/(public)/layout.tsx
docs/src/components/SideNav.css

Fixes https://github.com/mui/base-ui/issues/2136
Preview: https://deploy-preview-2194--base-ui.netlify.app/react/components/form
https://github.com/user-attachments/assets/78b94ff7-3066-44c8-afa1-c94ef6c8d84c

[docs] Fix sidebar jump

---

packages/react/src/menu/root/MenuRoot.tsx
packages/react/src/menubar/Menubar.test.tsx

Fixes https://github.com/mui/base-ui/pull/2156#issuecomment-3022283749

[menu] Check for parent menu for mouseenter state

---

CHANGELOG.md
docs/src/app/(public)/(content)/react/overview/releases/page.mdx

Fix encoded characters in changelog/releases page

[docs] Fix formatting of the changelog

---

packages/react/src/radio-group/RadioGroup.tsx

[radio group] Add aria-required attribute

---

packages/react/src/select/trigger/SelectTrigger.tsx

[select] Add `value` and `readOnly` to `Select.Trigger` state

---

packages/react/src/utils/detectBrowser.ts

[utils] Fix navigator checks and ensure safe platform retrieval

---

packages/react/src/accordion/root/AccordionRoot.tsx

[accordion] Destructure `render` prop

---

packages/react/src/composite/composite.ts
test/setupVitest.ts

Closes https://github.com/mui/base-ui/issues/2302

[composite] Check for `scrollTo` before scrolling

---

packages/react/src/collapsible/root/CollapsibleRoot.tsx

Same as https://github.com/mui/base-ui/pull/2280

[collapsible] Destructure render prop

---

packages/react/src/accordion/item/AccordionItem.test.tsx
packages/react/src/accordion/root/AccordionRoot.test.tsx
packages/react/src/accordion/root/AccordionRoot.tsx
packages/react/src/accordion/root/AccordionRootContext.ts
packages/react/src/accordion/trigger/AccordionTrigger.tsx

Fixes https://github.com/mui/base-ui/issues/2320

[accordion] Fix keyboard interactions with elements in the panel

---

packages/react/src/composite/composite.ts

Fixes https://github.com/mui/base-ui/issues/2328

[composite] Fix typo in `scrollIntoViewIfNeeded`

---

packages/react/src/select/item/SelectItem.test.tsx

[select] Fix test flake

---

packages/react/src/floating-ui-react/components/FloatingFocusManager.tsx
packages/react/src/popover/root/PopoverRoot.test.tsx

Fixes #2330
Different approach to #2331

[popover] Remove ancestor nodes from inside elements for outside press detection

---

docs/reference/generated/select-item.json
packages/react/src/select/item/SelectItem.tsx

[select] Update Select.Item label prop description

---

pnpm-lock.yaml

The lock file seems broken. 🤔 
https://app.circleci.com/pipelines/github/mui/base-ui/12322/workflows/f82426fd-5177-4e3d-9499-e63699c9ed83/jobs/123986

[code-infra] Fix lock file

---

packages/react/src/floating-ui-react/hooks/useDismiss.ts

[popover] Fix outside click after right clicking in popup

---

docs/src/app/(private)/experiments/scroll-area/inside-menu.module.css
docs/src/app/(private)/experiments/scroll-area/inside-menu.tsx
packages/react/src/scroll-area/root/ScrollAreaRoot.tsx

Scroll area scrollbars have the `data-hovering` attribute whilst hovering over elements in sibling portals. This is an issue for menus with scroll areas and submenus, as shown in the video below. The scrollbars should disappear when the submenu is hovered.
https://github.com/user-attachments/assets/e50b13a7-c1ed-432f-9f31-b84bc4f45e8a
The proposed fix is to prevent setting the `hovering` state to `true` if the pointer event's target is not a child of the scroll area.
https://github.com/user-attachments/assets/648043cf-3bdc-4c56-9038-795604e86299
https://deploy-preview-2542--base-ui.netlify.app/experiments/scroll-area/inside-menu
---
Note: I considered some other options. Firstly, I tried `event.stopPropagation()`in `handlePointerEnterOrMove()`, but it does not seem to have any effect. …

[scroll area] Prevent pointer events from sibling portals triggering hover

---

docs/src/app/(public)/(content)/react/components/alert-dialog/page.mdx
docs/src/app/(public)/(content)/react/components/dialog/page.mdx
docs/src/app/(public)/(content)/react/components/menu/page.mdx

Update references to `@base-ui/components`.

[docs] Update package import path in few examples

---

scripts/releaseChangelog.mts

Quick fix of the changelog generation script after label changes

[internal] Fix the changelog generation script

---

docs/src/app/(private)/experiments/toolbar/text-editor.tsx
docs/src/app/(public)/(content)/react/components/toolbar/demos/hero/css-modules/index.tsx
docs/src/app/(public)/(content)/react/components/toolbar/demos/hero/tailwind/index.tsx

This is a very minor PR aims to resolve errors in the Toolbar's text editor sample.

[docs] Eliminate errors in the Toolbar demos

---

docs/reference/generated/collapsible-panel.json

[collapsible] Fix generated files

---

package.json
packages/react/package.json
packages/utils/package.json
pnpm-lock.yaml

It is now part of the `build` command itself.

[code-infra] Remove copy-files scripts

---

packages/react/src/combobox/root/ComboboxRoot.test.tsx
packages/react/src/combobox/root/ComboboxRootInternal.tsx

The popup should only close in this scenario if the input isn't inside the popup.

[combobox] Fix unexpected close with multiple selection and input inside popup

---

renovate.json

Supported by the preset now: https://github.com/mui/mui-public/pull/738

[code-infra] Remove engines dependency updates for packages

---

packages/react/src/autocomplete/root/AutocompleteRoot.spec.tsx
packages/react/src/autocomplete/root/AutocompleteRoot.tsx
packages/react/src/combobox/collection/GroupCollectionContext.tsx
packages/react/src/combobox/group/ComboboxGroup.tsx
packages/react/src/combobox/group/ComboboxGroupContext.ts
packages/react/src/combobox/root/ComboboxRoot.spec.tsx
packages/react/src/combobox/root/ComboboxRoot.tsx
packages/react/src/combobox/root/ComboboxRootContext.tsx
packages/react/src/combobox/root/ComboboxRootInternal.tsx
packages/react/src/combobox/store.ts
packages/react/src/select/root/SelectRoot.spec.tsx
packages/react/src/select/root/SelectRoot.tsx
packages/react/src/select/store.ts
packages/react/src/utils/resolveValueLabel.tsx

Unlike `Array` it supports both `ReadonlyArray` + regular `Array`

[select][combobox][autocomplete] Use `ReadonlyArray` type for items

---

pnpm-lock.yaml

It's not important, but https://github.com/mui/base-ui/security/dependabot/60.

[dependencies] Bump Axios

---

docs/src/app/(private)/experiments/dialog.module.css
docs/src/app/(private)/experiments/menu/complex-nesting.tsx
docs/src/app/(private)/experiments/mobile-scroll-lock.module.css
docs/src/app/(private)/experiments/modality.module.css
docs/src/app/(private)/experiments/popups/popups-in-popups.module.css
docs/src/app/(public)/(content)/react/components/alert-dialog/demos/hero/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/alert-dialog/demos/hero/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/combobox/demos/creatable/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/combobox/demos/creatable/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/dialog/demos/close-confirmation/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/dialog/demos/close-confirmation/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/dialog/demos/hero/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/dialog/demos/hero/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/dialog/demos/nested/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/dialog/demos/nested/tailwind/index.tsx
docs/src/app/(public)/(content)/react/overview/quick-start/page.mdx
docs/src/app/(public)/layout.css
docs/src/components/MobileNav.css

Fixes #2799
Alternative to #2807

[docs] Fix backdrops on iOS 26

---

packages/react/src/combobox/input/ComboboxInput.test.tsx
packages/react/src/floating-ui-react/components/FloatingFocusManager.test.tsx
packages/react/src/floating-ui-react/components/FloatingFocusManager.tsx

Fixes https://github.com/mui/base-ui/pull/2860#pullrequestreview-3283149669

[combobox] Fix `focusout` of input not closing popup under certain conditions

---

docs/reference/generated/slider-root.json
docs/src/app/(public)/(content)/react/components/slider/demos/edge-alignment/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/slider/demos/edge-alignment/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/slider/page.mdx
packages/react/src/slider/root/SliderRoot.tsx

Changed to use the same design as hero

[docs] Update edge-aligned slider demo
