renovate.json

Instruct Renovate to batch MUI packages' updates instead of creating a separate PR for each one.
Also removed the unnecessary rule regarding Font Awesome packages (we don't use them in this repo).

[core] Group MUI package updates

---

packages/mui-base/src/TextareaAutosize/TextareaAutosize.test.tsx
packages/mui-base/src/TextareaAutosize/TextareaAutosize.tsx

Same as https://github.com/mui/material-ui/pull/41369. Applied it here. Fixes part of https://github.com/mui/base-ui/issues/168.

[TextareaAutosize] Fix inline style not getting applied

---

.github/workflows/no-response.yml

The no-response action keeps failing by exceeding GH API secondary rate limit: https://github.com/mui/base-ui/actions/workflows/no-response.yml
Since this action is triggered in all our repos, I changed its start time to occur later, hopefully preventing the issue.

[core] Change when the no-response action is triggered

---

test/README.md
test/karma.conf.js
test/karma.conf.profile.js

This PR updates browser versions in the BrowserStack config to match `.browserslistrc`:
- I've added the BrowserStack access token (from [here](https://www.notion.so/mui-org/BrowserStack-72953eaebde6421faf4644d3bd1641a5?pvs=4)) to the project in CircleCI, it wasn't there before (new repo!)
- Here's a successful job running all the updated browsers with `browserstack-force`: https://app.circleci.com/pipelines/github/mui/base-ui/387/workflows/b5119fff-1815-47f4-a481-7792f82727a9/jobs/2154/parallel-runs/0/steps/0-111

[test] Update karma config

---

netlify.toml

Netlify requires its Next.js apps to have hoisted dependencies (https://docs.netlify.com/frameworks/next-js/overview/#pnpm-support). In our case, however, hoisting the @mui/base package causes unintended behavior, as we have two different versions in the workspace (one as a dependency of @mui/material, the other - the version we develop). 
When the `shamefully-hoist` setting is used, the docs package ends up using the npm version of @mui/base, not the workspace one. Excluding this package from hoisting fixes the issue.

[core] Do not hoist the @mui/base package on Netlify

---

docs/src/modules/sandbox/Dependencies.test.js
docs/src/modules/sandbox/Dependencies.ts

Changed the demo codesandbox generator to correctly reference the @mui/base package built in a PR and use npm-published versions of other MUI packages.
Before: https://codesandbox.io/p/sandbox/recursing-burnell-km9sz4?file=%2Fpackage.json
After: https://codesandbox.io/p/sandbox/peaceful-goldwasser-mn5v9x?file=%2Fpackage.json

[core] Update Codesandbox preview to use the dev packages

---

babel.config.js
packages/mui-base/package.json
pnpm-lock.yaml
scripts/build.mjs
scripts/copyFiles.mjs

Removed the `legacy` and `modern` build targets. We'll ship standard ESM (once https://github.com/mui/material-ui/pull/41102 is complete and ready to be ported to Base UI) and CommonJS for Node.
Also removed the custom TS build script, as the issue it works around has been resolved.

[core] Simplify build scripts

---

packages/mui-base/src/Input/Input.tsx
packages/mui-base/src/TablePagination/TablePaginationActions.tsx
packages/mui-base/src/TablePagination/TablePaginationActions.types.ts
packages/mui-base/src/Transitions/CssAnimation.tsx
packages/mui-base/src/Transitions/CssTransition.tsx
scripts/generateProptypes.ts

Removed code unrelated to Base UI from the proptypes generator. Specifically, the most problematic part was a requirement to have a filename equal to the directory name (so TablePagination/TablePagination.tsx was picked up, but TablePagination/TablePaginationActions.tsx wasn't).
Also removed code specific to JS sources since the whole Base UI codebase is in TS.
These changes caused a couple of previously excluded components to have proptypes generated. This, in turn, caused a failing test in TablePaginationActions, where two mandatory props were not provided. As the props had their default value set in the code, I made them optional.

[core] Adapt proptypes generator to project needs

---

.eslintrc.js
packages/mui-base/test/conformanceTests/className.tsx
packages/mui-base/test/conformanceTests/propForwarding.tsx
packages/mui-base/test/conformanceTests/refForwarding.tsx
packages/mui-base/test/conformanceTests/renderProp.tsx
packages/mui-base/test/conformanceTests/utils.ts
packages/mui-base/test/describeConformance.tsx
packages/mui-base/test/describeConformanceUnstyled.tsx

Created the new conformance tests to be used in components with the new API. This will make the API docs builder correctly detect some of the components' features (like the underlying element).

[test] Create the conformance test suite for the new API

---

renovate.json

Do not attempt to upgrade packages to incompatible versions:
- chai >= 5.0 - requires tests in ESM (https://github.com/mui/base-ui/pull/118)
- unist-util-visit >= 3.0.0 - requires ESM (https://github.com/mui/base-ui/pull/129), can be removed once API docs builder is distributed through npm
- remark >= 14.0.0 - requires ESM (https://github.com/mui/base-ui/pull/123), can be removed once API docs builder is distributed through npm
Additionally moved the dependency update time window later, so it doesn't occur at the same time as the Core's.

[core] Disable updating packages to incompatible versions

---

renovate.json

This is a follow-up to #208, as I did not include all the dependencies.
- react-docgen - must be the same version as in api-docs-builder. Can be removed once this package is distributed through npm
- cimg/node (CircleCI docker image) - it should be consistent with the other Node.js packages
Also grouped all the MUI packages together as updating them separately doesn't make sense.

[core] Disable updating packages to incompatible versions (part 2)

---

.circleci/config.yml
packages/mui-base/src/useAutocomplete/useAutocomplete.test.js

As the React-next builds fail during dependency installation due to lockfile changes, this PR changes the installation command not to require a frozen lockfile.
This PR fixes the CI job and the failing useAutocomplete tests.

[core] Allow lockflile changes when building with React next

---

package.json
pnpm-lock.yaml

The stylelint-processor-styled-components became unnecessary with stylelint 15 (https://stylelint.io/migration-guide/to-15/#removed-processors-configuration-property). Removing this package also fixes https://github.com/mui/base-ui/security/dependabot/3

[core] Remove unnecessary stylelint-processor-styled-components

---

docs/pages/base-ui/api/use-switch.json
packages/mui-base/src/Switch/Switch.tsx
packages/mui-base/src/Switch/Switch.types.ts
packages/mui-base/src/useSwitch/useSwitch.ts
packages/mui-base/src/useSwitch/useSwitch.types.ts
packages/mui-base/src/utils/BaseUI.types.ts
packages/mui-base/src/utils/mergeReactProps.test.ts
packages/mui-base/src/utils/mergeReactProps.ts

This is an alternative to https://github.com/mui/base-ui/pull/209, which merges a user's external event handlers with our components' internal event handlers. Instead of needing to define every event handler with `mergeEventHandlers`, you just pass props normally through the function, and things get merged (including `style`) as expected. The other "mergeable" prop `className` is not considered, however.
One important part though is allowing to disambiguate preventing the browser's default behavior from preventing the library's logic.
React Event types are preserved here.
```js
mergeReactProps({
onPointerDown(event) {
// event is typed correctly + has this method:
event.preventBaseUIHandler();
} 
}, {
onPointerDown(event) {
console.log('this never runs');
}
})
```
We don't need a …

[core] Create `mergeReactProps` utility

---

packages/mui-base/test/conformanceTests/className.tsx
packages/mui-base/test/conformanceTests/renderProp.tsx

Taken from https://github.com/mui/base-ui/pull/186 into this individual PR.

[core] Adjust conformance tests to support portals

---

packages/mui-base/src/useSlider/useSlider.ts

Make it trigger as an immutable ref, for consistency with the rest of the codebase.
To be fair, I don't know if this PR (Option A) is the right long-term decision. We have two other options:
Option B
```diff
-const sliderRef = React.useRef<HTMLSpanElement>(null);
+const sliderRef = React.useRef<HTMLSpanElement>() as React.RefObject<HTMLSpanElement>;
```
Option C
```diff
-const sliderRef = React.useRef<HTMLSpanElement>(null);
+const sliderRef = React.useRef<HTMLSpanElement>();
```
I started a bit this with @romgrk in https://github.com/mui/mui-x/pull/11847#pullrequestreview-1847598552.
- Option A leads to more bundle size, but is consistent with how React sets null when unmounting. It also prevents reassignment mistakes. What's documented in https://react.dev/reference/react/useRef.
- …

[core][Slider] Ref immutable consistency

---

LICENSE

I noticed this in https://github.com/mui/pigment-css/pull/1#discussion_r1560772919. I'm changing this to replicate what we did in MUI X, and then Toolpad. See https://www.notion.so/mui-org/Legal-Public-company-info-e215ee76047940f48717b3c4ec9769b9?pvs=4#efcfb7aeda4f4feb961ee91ee43413b3 for why.

[core] Fix license entity reference

---

scripts/releaseTag.mjs

The releaseTag script had references to the Core repository. Changed them to the Base UI one.

[core] Change the references to the Material UI repo in the releaseTag script

---

packages/mui-base/src/NumberField/NumberFieldScrubArea.test.tsx
packages/mui-base/src/NumberField/NumberFieldScrubAreaCursor.test.tsx
packages/mui-base/src/useNumberField/useScrub.ts

Draft to experiment, these somehow started failing after merge

[NumberField] Fix failing browser tests

---

scripts/README.md

Added how to publish the docs on the Netlify site to the scripts' README.

[core] Describe how to publish the docs

---

.browserslistrc
.circleci/config.yml
.eslintignore
.gitignore
babel.config.js
docs/babel.config.js
docs/next.config.mjs
pnpm-workspace.yaml

Removed aliases from docs' Babel config, following up on https://github.com/mui/material-ui/pull/40792.
Also cleaned up the Babel and Next configs, removing `@ts-ignore`s and references to benchmark tests (we don't have them in this repo).

[core] Config cleanup

---

docs/data/base/components/tabs/tabs.md

Match with https://mui.com/x/react-data-grid/accessibility/#navigation.
Why upper case? We copied https://www.w3.org/WAI/ARIA/apg/patterns/listbox/. MDN uses a different style https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/slider_role#examples but 🤷‍♂️
Why right aligned? I guess it's simpler to scan?
Preview: https://deploy-preview-397--base-ui.netlify.app/base-ui/react-tabs/#accessibility

[docs] Consistent arrow style

---

docs/pages/base-ui/api/tab-indicator.json
docs/pages/base-ui/api/tab-panel.json
docs/pages/base-ui/api/tab.json
packages/mui-base/src/Tabs/Root/TabsRoot.tsx
packages/mui-base/src/Tabs/index.barrel.ts
packages/mui-base/src/Tabs/index.ts
scripts/buildApiDocs/config/getComponentImports.ts

Import instruction for several tabs components were incorrect:
Now fixed:
Preview: https://deploy-preview-401--base-ui.netlify.app/base-ui/react-tabs/components-api

[docs] Fix incorrect Tabs import instructions

---

docs/data/base/components/checkbox/checkbox.md
docs/data/base/components/number-field/number-field.md
docs/data/base/components/switch/switch.md
docs/data/base/components/tabs/tabs.md

The Bundlephobia links in the components docs' headers (the "Bundle size" pill under the header) incorrectly pointed to `@mui/base`. Once we have just one docs site for Base UI, we'll be able to change the package name globally, in a shared package #422, but for the time being, we have to update each page manually.
https://github.com/mui/material-ui/blob/a55cd51ab4312fd2864dbd59e78a2ed8b5aae3dc/packages/mui-docs/src/ComponentLinkHeader/ComponentLinkHeader.tsx#L34
Preview: https://deploy-preview-419--base-ui.netlify.app/base-ui/react-checkbox

[docs] Correct Bundlephobia links

---

docs/data/base/components/tooltip/tooltip.md

After https://github.com/mui/base-ui/pull/378 was merged, we have to use @mui/docs/ComponentLinkHeader for the docs. Without it, building the docs fails.

[Tooltip][docs] Use the correct version of ComponentLinkHeader

---

renovate.json

Our current Renovate settings prevented it from updating pnpm. This PR (hopefully) fixes it.

[core] Allow Renovate to update pnpm

---

README.md
docs/data/base/components/alert-dialog/alert-dialog.md
docs/data/base/components/checkbox/checkbox.md
docs/data/base/components/dialog/dialog.md
docs/data/base/components/number-field/number-field.md
docs/data/base/components/switch/switch.md
packages/mui-base/src/legacy/README.md

Those errors can be seen by running
`vale sync && git ls-files | grep -h ".md$" | xargs vale --filter='.Level=="error"'`
It's not in the CI yet because we share the config with the monorepo HEAD, which could mean breaking the CI in Base UI as soon as a PR is merged in the monorepo.
https://github.com/mui/base-ui/blob/25eb16b271c6e704bb261bb4df71b6951c0a5585/.vale.ini#L10
We will need to change this.

[docs] Fix Vale errors

---

packages/mui-base/src/NumberField/Input/NumberFieldInput.test.tsx
packages/mui-base/src/NumberField/Root/NumberFieldRoot.test.tsx
packages/mui-base/src/NumberField/utils/format.test.ts
packages/mui-base/src/NumberField/utils/parse.test.ts

Fixed the NumberInput tests failing on machines with non-English locales.
Tested on my local Windows PC with Polish regional settings.
Fixes #516

[NumberField] Fix tests on non-English locale machines

---

packages/mui-base/src/Progress/index.ts
packages/mui-base/src/Slider/index.ts

Next.js build complains about several exports (see https://app.netlify.com/sites/base-ui/deploys/66c2fdcd3b18260008132343).
Explicitly marking them as types solves the issue.

[typescript] Add `type` to export statements

---

docs/.link-check-errors.txt
docs/scripts/reportBrokenLinks.js

I saw the issue from #493, it looked strange to have errors from the source not owned in this repository.
A bit related to https://github.com/mui/material-ui/pull/43144.
Also noticed a regression from https://github.com/mui/material-ui/pull/41240. Fixed in https://github.com/mui/material-ui/commit/8f9cf1f6ac788039e47c13e55686ad4adac95eff.

[docs] Fix pnpm docs:link-check script

---

test/karma.conf.js

Revert the change made in https://github.com/mui/base-ui/pull/546 as Browserstack often times out due to limited resources.

[test] Run Browserstack tests on master only

---

packages/mui-base/src/Menu/Positioner/MenuPositioner.tsx
packages/mui-base/src/Popover/Positioner/PopoverPositioner.tsx
packages/mui-base/src/PreviewCard/Positioner/PreviewCardPositioner.tsx
packages/mui-base/src/Tooltip/Positioner/TooltipPositioner.tsx

[Docs says ](https://deploy-preview-580--base-ui.netlify.app/base-ui/react-menu/components-api/#menu-positioner-props)default value of `collsionBoundary` prop is `clippingAncestors` but it's not defined anywhere. This PR adds  missing default values.

Add  default value as `clippingAncestors` to collisionBoundary prop

---

docs/src/components/EditPageGithubLink.tsx

Quick-win I saw on #613. It's a regression from previous docs-infra:
- We don't need to add `noreferrer` anymore: https://github.com/mui/material-ui/pull/40447.
- However, I don't think we want to waste SEO crawling budget and page rank on those links, so added `nofollow` to keep the juice for our internal links.

[docs] Fix rel attribute on edit GitHub links

---

packages/mui-base/src/Tabs/TabIndicator/TabIndicator.test.tsx

BrowserStack tests failed in Safari again: https://app.circleci.com/pipelines/github/mui/base-ui/3660/workflows/b29d3072-6e5a-4368-8098-233d58bd43cf/jobs/24143
To make them more reliable, I changed a fixed timeout to `waitFor` call.

[test] Use `waitFor` instead of fixed timeout in tests

---

test/README.md

I was browisng through core's test ReadMe, found istanbul package url is wrong and same wrong url is used here as well, opened PR to update it
previous url: https://istanbul-js.org/ (Site not found)
updated url: https://istanbul.js.org/
core repo PR: https://github.com/mui/material-ui/pull/43935

[test] Point Istanbul to correct URL

---

packages/mui-base/src/Dialog/Popup/useDialogPopup.tsx
packages/mui-base/src/NumberField/ScrubAreaCursor/NumberFieldScrubAreaCursor.tsx
packages/mui-base/src/Slider/Root/useSliderRoot.ts
packages/mui-base/src/utils/useScrollLock.ts

[core] Reference `ownerDocument`

---

docs/data/api/menu-positioner.json
docs/data/api/popover-positioner.json
docs/data/api/preview-card-positioner.json
docs/data/api/tooltip-positioner.json
docs/data/translations/api-docs/menu-positioner/menu-positioner.json
docs/data/translations/api-docs/popover-positioner/popover-positioner.json
docs/data/translations/api-docs/preview-card-positioner/preview-card-positioner.json
docs/data/translations/api-docs/tooltip-positioner/tooltip-positioner.json
docs/src/components/DocsVersionSelector.tsx
packages/mui-base/src/Menu/Positioner/MenuPositioner.tsx
packages/mui-base/src/Menu/Positioner/useMenuPositioner.ts
packages/mui-base/src/Popover/Positioner/PopoverPositioner.tsx
packages/mui-base/src/Popover/Positioner/usePopoverPositioner.tsx
packages/mui-base/src/PreviewCard/Positioner/PreviewCardPositioner.tsx
packages/mui-base/src/PreviewCard/Positioner/usePreviewCardPositioner.ts
packages/mui-base/src/Tooltip/Positioner/TooltipPositioner.tsx
packages/mui-base/src/Tooltip/Positioner/useTooltipPositioner.ts
packages/mui-base/src/utils/useAnchorPositioning.ts

[core] Rename positionStrategy to positionMethod

---

test/regressions/TestViewer.js

Propagate https://github.com/mui/material-ui/pull/43656, one small iteration on https://github.com/mui/mui-public/issues/199
I noticed this by chance from #707.
What's the value? For example, it surfaces how this demo https://master--base-ui.netlify.app/components/react-number-field/ is broken once exported to codesandbox. Meaning, once a developer copy & paste it in its project.

[test] Improve visual screenshot canva

---

packages/mui-base/src/Fieldset/Legend/FieldsetLegend.tsx
packages/mui-base/src/Fieldset/Legend/FieldsetLegend.types.ts
packages/mui-base/src/Fieldset/Legend/useFieldsetLegend.ts
packages/mui-base/src/Fieldset/Root/FieldsetRoot.tsx
packages/mui-base/src/Fieldset/Root/FieldsetRoot.types.ts
packages/mui-base/src/Fieldset/Root/FieldsetRootContext.ts
packages/mui-base/src/Fieldset/index.barrel.ts
packages/mui-base/src/Fieldset/index.ts

[Fieldset] Move types to namespaces

---

test/regressions/TestViewer.js

This wasn't correctly migrated from emotion style: https://github.com/mui/material-ui/blob/860ccd0e5a8f38e8149977ba4bb46c71ae7e894c/test/regressions/TestViewer.js#L68
I noticed this by chance from #665.

[test] Fix correct box-sizing reset in visual tests

---

packages/mui-base/src/Checkbox/Root/CheckboxRoot.test.tsx
packages/mui-base/src/Dialog/Root/DialogRoot.test.tsx
packages/mui-base/src/Menu/CheckboxItem/MenuCheckboxItem.test.tsx
packages/mui-base/src/Menu/Item/MenuItem.test.tsx
packages/mui-base/src/Menu/RadioItem/MenuRadioItem.test.tsx
packages/mui-base/src/Menu/Root/MenuRoot.test.tsx
packages/mui-base/src/Menu/Trigger/MenuTrigger.test.tsx
packages/mui-base/src/NumberField/Input/NumberFieldInput.test.tsx
packages/mui-base/src/NumberField/Root/NumberFieldRoot.test.tsx
packages/mui-base/src/Popover/Root/PopoverRoot.test.tsx
packages/mui-base/src/PreviewCard/Root/PreviewCardRoot.test.tsx
packages/mui-base/src/RadioGroup/Root/RadioGroupRoot.test.tsx
packages/mui-base/src/Slider/Root/SliderRoot.test.tsx
packages/mui-base/src/Switch/Root/SwitchRoot.test.tsx
packages/mui-base/src/Tabs/Root/TabsRoot.test.tsx
packages/mui-base/src/Tabs/TabsList/TabsList.test.tsx
packages/mui-base/src/Tooltip/Root/TooltipRoot.test.tsx

~Those `async` functions are noise, see the source of Act if you want to be sure: https://github.com/facebook/react/blob/main/packages/react/src/ReactAct.js.~
Edit: Ok, no, this look required https://github.com/mui/mui-public/issues/174

[test] Add missing async

---

docs/data/api/field-error.json
docs/data/api/field-root.json
docs/data/components/field/UnstyledFieldAsync.js
docs/data/components/field/UnstyledFieldAsync.tsx
docs/data/components/field/UnstyledFieldIntroduction/system/index.js
docs/data/components/field/UnstyledFieldIntroduction/system/index.tsx
docs/data/components/field/field.mdx
docs/data/translations/api-docs/field-error/field-error.json
docs/data/translations/api-docs/field-root/field-root.json
packages/mui-base/src/Field/Control/useFieldControlValidation.ts
packages/mui-base/src/Field/Error/FieldError.test.tsx
packages/mui-base/src/Field/Error/FieldError.tsx
packages/mui-base/src/Field/Root/FieldRoot.test.tsx
packages/mui-base/src/Field/Root/FieldRoot.tsx
packages/mui-base/src/Field/Root/FieldRootContext.ts
packages/mui-base/src/NumberField/Root/useNumberFieldRoot.ts

---
- `Field.Error`: `show` -> `match`
- `Field.Root`: `validateOnChange` -> `validationMode: 'onChange'` (`onBlur` default)
- `Field.Root`: `validateDebounceTime` -> `validationDebounceTime`
Unhandled: `validationMode: 'all'` for both simultaneously. The docs demos don't seem to need this - wait until a use case appears?

[Field] Update APIs

---

.browserslistrc
packages/mui-base/package.json

Same minimum version increase as in https://github.com/mui/material-ui/pull/42920, from v12.0.0 to v14.0.0. No reason for the version to be different.

[core] Increase the minimum Node.js version support to 14.0.0

---

.gitignore

Fixes a regression introduced in https://github.com/mui/base-ui/pull/746
Properly ignores playgrounds.

[core] Fix gitignore to exclude playgrounds

---

docs/vitest.config.ts
test/setupVitest.ts

The code that sets up polyfills for JSDOM did not correctly detect when JSDOM is enabled. This PR fixes this issue.
Appeared in https://github.com/mui/base-ui/pull/764#issuecomment-2445010181

[test] Fix JSDOM detection in tests

---

docs/data/components/text-input/text-input.mdx

Removed a trailing slash from a link that was triggering a failure in https://app.circleci.com/pipelines/github/mui/base-ui/4430/workflows/ef320ba1-f2dd-4d6a-a306-116d7a862ccd/jobs/29845

[docs] Remove trailing slash from link

---

.vale.ini
CHANGELOG.md
docs/data/components/accordion/accordion.mdx
docs/data/components/collapsible/collapsible.mdx
docs/data/components/menu/menu.mdx

A quick fix for a regression that I noticed while fixing https://github.com/mui/material-ui/pull/44277. We were no longer linting the docs. This got broken with #538.
Ideally, we could use https://github.com/errata-ai/vale/issues/841, but it's not there. Instead, there are a bunch of examples online on how this can be done https://github.com/search?q=%5Bformats%5D+mdx+%3D+md&type=code.
We will need to propagate this to the other repositories. But unclear if we should do it just yet, we might want to wait.
Point 20. of https://github.com/mui/base-ui/issues/588 doesn't make it super clear that MDX is compatible with a great UX for developers. I imagine that it's solvable, but it's it's not it seems to mean that we need to remove MDX and go back to the previous approach that yields better …

[docs-infra] Add mdx support to vale lint

---

packages/mui-base/src/Checkbox/Root/CheckboxRoot.tsx
packages/mui-base/src/CheckboxGroup/Parent/useCheckboxGroupParent.test.tsx
packages/mui-base/src/CheckboxGroup/Parent/useCheckboxGroupParent.ts

[CheckboxGroup] Handle disabled children

---

packages/mui-base/src/Composite/Root/CompositeRoot.test.tsx
packages/mui-base/src/Composite/Root/CompositeRoot.tsx
packages/mui-base/src/Composite/Root/useCompositeRoot.ts
packages/mui-base/src/Composite/composite.ts
packages/mui-base/src/RadioGroup/Root/RadioGroupRoot.test.tsx
packages/mui-base/src/RadioGroup/Root/RadioGroupRoot.tsx
packages/mui-base/src/utils/hasComputedStyleMapSupport.ts

Split from https://github.com/mui/base-ui/pull/763 to unblock https://github.com/mui/base-ui/pull/751
Closes https://github.com/mui/base-ui/issues/824
- Adds support for RTL navigation with arrow keys by detecting the CSS `direction` property that could be inherited from the HTML `dir` attribute
- Adds support for navigating to the first/last items with Home/End keys, enable-able with the `enableHomeAndEndKeys` prop

[Composite] Support RTL navigation, Home/End keys

---

docs/data/api/slider-root.json
docs/data/translations/api-docs/slider-root/slider-root.json
docs/reference/generated/slider-root.json
docs/reference/overrides/slider-root.json
packages/mui-base/src/Menu/RadioGroup/MenuRadioGroup.tsx
packages/mui-base/src/Menu/Root/MenuRoot.tsx
packages/mui-base/src/Menu/Root/useMenuRoot.ts
packages/mui-base/src/Popover/Root/usePopoverRoot.ts
packages/mui-base/src/PreviewCard/Root/usePreviewCardRoot.ts
packages/mui-base/src/Radio/Root/useRadioRoot.tsx
packages/mui-base/src/RadioGroup/Root/RadioGroupRoot.tsx
packages/mui-base/src/RadioGroup/Root/RadioGroupRootContext.ts
packages/mui-base/src/Slider/Root/SliderRoot.test.tsx
packages/mui-base/src/Slider/Root/SliderRoot.tsx
packages/mui-base/src/Slider/Root/useSliderRoot.ts
packages/mui-base/src/Switch/Root/useSwitchRoot.ts
packages/mui-base/src/Tabs/Root/TabsRoot.tsx
packages/mui-base/src/Tabs/Root/TabsRootContext.ts
packages/mui-base/src/Tabs/Root/useTabsRoot.ts
packages/mui-base/src/Tabs/TabsList/useTabsList.ts
packages/mui-base/src/Tooltip/Root/useTooltipRoot.ts

- Renamed the first parameter to match the callback name (`value` in `onValueChange`, `checked` in `onCheckedChange`, etc.).
- Using native events in all public event handlers.
- Renamed `SliderRoot.onValueChange` second parameter to `activeThumbIndex` and moved it to the third position.

[core] Make callback parameters consistent

---

docs/src/app/new/(content)/layout.tsx
docs/src/components/TableCode.tsx
docs/src/getChildrenText.ts
docs/src/mdx-components.tsx

[docs] Automatic title and meta description

---

packages/react/src/alert-dialog/root/AlertDialogRoot.tsx
packages/react/src/dialog/popup/useDialogPopup.tsx
packages/react/src/dialog/root/DialogRoot.test.tsx
packages/react/src/dialog/root/DialogRoot.tsx
packages/react/src/dialog/root/useDialogRoot.ts
packages/react/src/menu/root/MenuRoot.test.tsx
packages/react/src/menu/root/useMenuRoot.ts
packages/react/src/popover/root/PopoverRoot.test.tsx
packages/react/src/popover/root/usePopoverRoot.ts
packages/react/src/preview-card/root/PreviewCardRoot.test.tsx
packages/react/src/preview-card/root/usePreviewCardRoot.ts
packages/react/src/select/root/SelectRoot.test.tsx
packages/react/src/select/root/useSelectRoot.ts
packages/react/src/utils/types.ts
packages/react/src/utils/useUnmountAfterCloseAnimation.tsx

When popups are closed programatically, the code that unmounts them after their exit animations finish wasn't run. 
In this PR I moved the exit animation detection to an effect, so it runs whenever the state changes. Added tests in all affected components (and fixed few other issues with the Dialog: `animated` prop not being propagated to `useDialogRoot` and `aria-hidden` being applied next to `inert`)

[popups] Look for animations when `open` is set to `false` externally

---

docs/src/app/experiments/collapsible-transitions.tsx
docs/src/app/experiments/collapsible.module.css
packages/react/src/collapsible/root/useCollapsibleRoot.ts
packages/react/src/utils/useTransitionStatus.ts

Split from https://github.com/mui/base-ui/pull/807#issuecomment-2500516332 since `keepMounted={false}` needs some rework
Collapsible depends on having 1 frame between `open` and `entering` to measure the size of the panel contents
https://deploy-preview-887--base-ui.netlify.app/experiments/collapsible-transitions

[core] Optionally delay `useTransitionStatus`'s `entering` status with a param

---

package.json
pnpm-lock.yaml

I noticed some changes when running pnpm i/pnpm dedupe whe using a newer version of pnpm. Pinning the pnpm's version in the engines definition will eliminate this problem.

[core] Pin pnpm's version

---

docs/data/components/preview-card/UnstyledPreviewCardIntroduction/system/index.js
docs/data/components/preview-card/UnstyledPreviewCardIntroduction/system/index.tsx
docs/src/app/layout.tsx

We recently changed https://x.com/base_ui to use lowercase as it's more common to see as a slug.

[core] Fix Twitter link to Base UI

---

docs/package.json
pnpm-lock.yaml

We don't use the dependency, I noticed it as renovate was trying to upgrade it: https://github.com/mui/base-ui/pull/926. I suppose we stopped using when we removed the editable demos feature, but the dependency was never removed.

[core] Remove unused dependency

---

docs/src/components/CodeBlock.css
docs/src/components/MobileNav.tsx
docs/src/components/Table.css
docs/src/styles.css

Fixes the flicker on some scroll containers in iOS Safari when the mobile nav is opened
Before
https://github.com/user-attachments/assets/1f252424-0f1f-4ae7-b65e-f45df0b36383
After
https://github.com/user-attachments/assets/17cbc01e-0a18-4c23-98d9-f3badbc506f6

[docs] Work around iOS Safari flicker

---

packages/react/src/collapsible/panel/CollapsiblePanel.test.tsx
packages/react/src/collapsible/panel/useCollapsiblePanel.ts
packages/react/src/collapsible/root/CollapsibleRoot.test.tsx

Closes https://github.com/mui/base-ui/issues/1024

[Collapsible] Fix trigger `aria-controls` referencing nonexistent `id`

---

packages/react/src/collapsible/panel/useCollapsiblePanel.ts
packages/react/src/dialog/root/DialogRoot.test.tsx
packages/react/src/menu/root/MenuRoot.test.tsx
packages/react/src/popover/root/PopoverRoot.test.tsx
packages/react/src/preview-card/root/PreviewCardRoot.test.tsx
packages/react/src/select/root/SelectRoot.test.tsx
packages/react/src/utils/useAfterExitAnimation.tsx
packages/react/src/utils/useAnimationsFinished.ts

Closes #979
Addresses the `alignOptionToTrigger` non-animated use case of #965
`runOnceAnimationsFinish` is wrapped in a `requestAnimationFrame` (to know the ending styles) and then a microtask. By flushing the `setMounted` state update synchronously, the browser won't paint, leading to no flicker.

[useAfterExitAnimation] `flushSync` the `onFinished` call

---

docs/src/components/reference/rehypeReference.mjs

Closes https://github.com/mui/base-ui/issues/1031
After the change: https://deploy-preview-1056--base-ui.netlify.app/react/components/menu#radio-item-indicator

[docs] Remove space from part names but preserve anchor urls

---

docs/src/app/(public)/(content)/react/components/switch/demos/hero/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/switch/demos/hero/tailwind/index.tsx
docs/src/app/(public)/layout.css
docs/src/components/Header.css
docs/src/components/Select.tsx
docs/src/components/SideNav.tsx
docs/src/components/demo/Demo.css
docs/src/components/demo/DemoSourceBrowser.tsx

- Add focus outline to the switch demo
- Fix the demo code block accessibility violation
- Fix horizontal space on mobile
- Fix a screen reader issue with the docs select component
- Reduce docs min width to `320px`
- Bump up the timeout to force hide the scrollbar after the programmatic scroll in side nav

[docs] Various fixes and cleanup

---

packages/react/src/utils/reactVersion.ts

Same as https://github.com/mui/material-ui/pull/43820
```js
parseInt('19.0.0-rc.12131', 10); // returns 19
```
---
**Off topic**. I could see us creating an internal helper and exposing fit from Base UI, this duplication feels off:
- https://github.com/mui/mui-x/blob/46c46ff829ed601387048d5da99d156967226980/packages/x-internals/src/reactMajor.ts#L3
- https://github.com/mui/material-ui/blob/6b5d751b0c7f46919cca75238b3da7ee751ac8a6/packages/mui-utils/src/getReactElementRef/getReactElementRef.ts#L12
- https://github.com/mui/material-ui/blob/6b5d751b0c7f46919cca75238b3da7ee751ac8a6/packages/mui-base/src/Input/Input.test.tsx#L285
- MUI X and Material UI tests use `reactMajor } from '@mui/internal-test-utils';` but the source use something different? Doesn't make much sense.
A possible path:
- …

[core] Simplify isReactVersionAtLeast()

---

packages/react/src/utils/visuallyHidden.ts

Prevents scrollbars from appearing when the natural position of the visually hidden element exceeds viewport width (e.g. it is in a scroll container)
https://mui-org.slack.com/archives/C02P87NQLJC/p1734038721374039
Issue at hand
Uploading Screen Recording 2024-12-12 at 22.20.42.mov…

[visuallyHidden] Set top left position

---

docs/src/app/(public)/(content)/react/components/accordion/demos/hero/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/accordion/demos/hero/css-modules/index.tsx
docs/src/app/(public)/(content)/react/components/accordion/demos/hero/tailwind/index.tsx
docs/src/components/Popup.css
docs/src/components/Select.tsx
docs/src/components/Table.css
docs/src/components/TableCode.tsx
docs/src/components/demo/DemoVariantSelector.tsx
docs/src/components/reference/AttributesTable.tsx
docs/src/components/reference/CssVariablesTable.tsx
docs/src/components/reference/PropsTable.tsx
docs/src/components/reference/rehypeReference.mjs
docs/src/syntax-highlighting/index.css
docs/src/syntax-highlighting/rehypeInlineCode.mjs

Fixes unnecessary empty props tables:
Fixes occasional stray pixels when table cells overflow
Increases the width of the first column in API reference tables to fit the CSS variable names:

[docs] API reference fixes/improvements

---

docs/src/app/not-found.tsx
docs/src/components/Link.tsx
docs/src/mdx-components.tsx

Example external links on the about page: https://deploy-preview-1071--base-ui.netlify.app/react/overview/about
Closes https://github.com/mui/base-ui/issues/1033

[docs] Generate external links from mdx

---

docs/src/components/TableCode.tsx
docs/src/components/reference/AttributesTable.tsx
docs/src/components/reference/CssVariablesTable.tsx
docs/src/components/reference/PropsTable.tsx
docs/src/components/reference/ReferenceTablePopover.tsx
docs/src/mdx-components.tsx

- Expose descriptions for data attributes and CSS variables
- Tweak reference tables column widths
- Improve table code formatter
- Handle union types when returned by a solo function:
- Sturdier handling of nested union types
https://deploy-preview-1086--base-ui.netlify.app/

[docs] Expose data attrs descriptions and improve table code formatter

---

docs/reference/generated/menu-trigger.json
docs/reference/generated/select-trigger.json
packages/react/src/menu/trigger/MenuTrigger.tsx
packages/react/src/select/trigger/SelectTrigger.tsx

[Menu, Select] Do not ignore the Trigger's `label` prop

---

docs/src/components/Header.tsx

The version was hard coded, I reverted back the logic to use the root's package.json version.

[docs] Use the root package.json version

---

docs/src/components/quick-nav/QuickNav.tsx

Fixes this issue when the quick nav positioning math wasn't aware of scroll locking
https://github.com/user-attachments/assets/e10c779f-8f08-41dc-8ca4-5f845badb2b0

[docs] Account for the scroll lock in quick nav

---

docs/src/app/(public)/(content)/layout.tsx
docs/src/app/(public)/layout.tsx
docs/src/app/(public)/page.tsx
docs/src/app/layout.tsx
docs/src/styles.css

Updated desktop Safari browser header theme to feel distinct from the site header / site background:
https://github.com/user-attachments/assets/7b208b92-6a97-4424-9887-1a41f5cc2273
***
Updated mobile Safari browser header theme to blend with the site header / site background:
https://github.com/user-attachments/assets/7f267daf-4f34-4521-ad3b-4e32a06e1483
***
Updated scroll anchors to use native smooth scrolling:
https://github.com/user-attachments/assets/ce220110-03e2-407d-8068-0610f5870b6a
***
Added `overflow-y: scroll` to `html` for a stable scrollbar

[docs] Viewport tweaks

---

packages/react/src/utils/useScrollLock.ts

Docs scroll locking on iOS has been bugged since I added the following style to maintain a stable gutter for hard scrollbars in [#1096](https://github.com/mui/base-ui/pull/1096):
```
html {
overflow-y: scroll
}
```
(I don't want to use `scrollbar-gutter` because it is not supported in Safari and renders page background instead of an empty scrollbar, which looks weird with our design)
on iOS this causes two things:
- Scrolling up while scroll is locked makes the html element catch the scroll
- If you start scrolling down after that, you are scrolling the contents behind the dialog

[use-scroll-lock] Fix iOS html overflow

---

docs/src/app/(public)/(content)/react/components/accordion/page.mdx
docs/src/app/(public)/(content)/react/components/alert-dialog/page.mdx
docs/src/app/(public)/(content)/react/components/checkbox/page.mdx
docs/src/app/(public)/(content)/react/components/collapsible/page.mdx
docs/src/app/(public)/(content)/react/components/dialog/page.mdx
docs/src/app/(public)/(content)/react/components/field/page.mdx
docs/src/app/(public)/(content)/react/components/fieldset/page.mdx
docs/src/app/(public)/(content)/react/components/menu/page.mdx
docs/src/app/(public)/(content)/react/components/number-field/page.mdx
docs/src/app/(public)/(content)/react/components/popover/page.mdx
docs/src/app/(public)/(content)/react/components/preview-card/page.mdx
docs/src/app/(public)/(content)/react/components/progress/page.mdx
docs/src/app/(public)/(content)/react/components/scroll-area/page.mdx
docs/src/app/(public)/(content)/react/components/select/page.mdx
docs/src/app/(public)/(content)/react/components/slider/page.mdx
docs/src/app/(public)/(content)/react/components/switch/page.mdx
docs/src/app/(public)/(content)/react/components/tabs/page.mdx
docs/src/app/(public)/(content)/react/components/tooltip/page.mdx

"place its parts the following way" struck me as awkward phrasing—how about "assemble ~it as shown below~ its parts"?

[docs] Improve API reference copy

---

packages/react/package.json
pnpm-lock.yaml

We don't merge classes with clsx in the library.

[core] Remove unused clsx dependency

---

packages/react/src/alert-dialog/backdrop/AlertDialogBackdrop.tsx
packages/react/src/alert-dialog/popup/AlertDialogPopup.test.tsx
packages/react/src/alert-dialog/popup/AlertDialogPopup.tsx
packages/react/src/alert-dialog/root/AlertDialogRoot.tsx
packages/react/src/alert-dialog/root/AlertDialogRootContext.ts
packages/react/src/dialog/backdrop/DialogBackdrop.tsx
packages/react/src/dialog/popup/DialogPopup.test.tsx
packages/react/src/dialog/popup/DialogPopup.tsx
packages/react/src/dialog/root/DialogRoot.tsx
packages/react/src/dialog/root/DialogRootContext.ts

Added the `data-nested` style hook and removed `data-nested-dialogs` from Dialog.Popup and AlertDialog.Popup.

[Dialog, AlertDialog] Add the `nested` style hook

---

docs/src/app/(public)/(content)/react/overview/releases/page.mdx

Having the versions in the table of content is much better for searchability than the dates. I moved the date after the header.

[docs] Release header improvement

---

docs/reference/generated/alert-dialog-popup.json
docs/reference/generated/dialog-popup.json
packages/react/src/alert-dialog/popup/AlertDialogPopup.test.tsx
packages/react/src/alert-dialog/popup/AlertDialogPopup.tsx
packages/react/src/alert-dialog/popup/AlertDialogPopupDataAttributes.ts
packages/react/src/dialog/popup/DialogPopup.test.tsx
packages/react/src/dialog/popup/DialogPopup.tsx
packages/react/src/dialog/popup/DialogPopupDataAttributes.ts

Adds the style hook when the Dialog/AlertDialog has open subdialogs (of the same type)

[Dialog, AlertDialog] Add the `data-has-nested-dialogs` hook

---

docs/src/components/CodeBlock.tsx
docs/src/components/MobileNav.css
docs/src/components/MobileNav.tsx

- Wait for the URL to change before closing the mobile nav dialog. Otherwise, there might be a slight flash of content during the close animation as the navigation happens. This guarantees that closing the nav dialog smoothly “reveals” the new page.
- If navigating to the same page, close the nav and scroll up smoothly.
- Fix the flick down gesture animation after https://github.com/mui/base-ui/pull/1109 (we relied on the scroll lock to be on during the flick down)

[docs] Mobile nav fixes

---

docs/src/app/(public)/(content)/react/components/dialog/demos/nested/css-modules/index.tsx
docs/src/app/(public)/(content)/react/components/dialog/demos/nested/tailwind/index.tsx

Can't see the nesting on a small screen because the child dialog is taller due to a line break

[docs] Nested dialogs nit

---

docs/data/getting-started/usage/usage.mdx
docs/src/app/(public)/(content)/react/handbook/composition/page.mdx

Fixes render prop example to match variable and naming from other examples.

[docs] Fix composition render prop example for internalState naming

---

docs/src/app/(private)/experiments/scroll-lock.tsx
docs/src/components/CodeBlock.css
docs/src/components/Demo/Demo.css
docs/src/components/MobileNav.tsx
docs/src/components/QuickNav/QuickNav.tsx
docs/src/components/Table.css
packages/react/package.json
packages/react/src/utils/detectBrowser.ts
packages/react/src/utils/useScrollLock.ts
pnpm-lock.yaml

Closes #1156
A new custom implementation is used across non-iOS browsers, handling the previous edge cases on Firefox as well, removing the patch we gave it.
As far as I can tell, scroll containers are optimized in iOS similar to the `will-change` property (adding it causes the flicker everywhere), possibly due to some compositing step in the browser when animations are occurring when scrolled down(?). The new implementation on iOS also flickered, but even worse and had other issues.
For iOS, there seems to be 3 options:
1. Accept that iOS has this flicker issue and has workarounds (like we did on the docs for the main nav). We could make this easier, maybe?
2. Use a scroll lock dependency just for iOS, or browsers without inset scrollbars.
3. Accept that iOS can't lock scroll at all …

[useScrollLock] New implementation

---

docs/src/components/QuickNav/QuickNav.css
docs/src/components/QuickNav/QuickNav.tsx

Prevent quick nav from adjusting the position if its height is similar to viewport height and the scroll difference would be unimportant
Avoids unnecessary movement
https://github.com/user-attachments/assets/ef9a5107-82db-4b9b-958d-c9102db06970

[docs] Skip unnecessary position changes when quick nav height is similar to viewport

---

docs/src/components/Demo/DemoSourceBrowser.tsx
docs/src/components/QuickNav/QuickNav.css
docs/src/components/QuickNav/QuickNav.tsx
docs/src/components/QuickNav/rehypeQuickNav.mjs

Put quick nav before the h1 so that clicking anything in the main page contents sets initial focus after the quick nav
(MDN does a similar thing)

[docs] Quick nav actually first

---

packages/react/src/alert-dialog/popup/AlertDialogPopup.test.tsx
packages/react/src/alert-dialog/root/AlertDialogRootContext.ts
packages/react/src/dialog/popup/DialogPopup.test.tsx
packages/react/src/dialog/root/DialogRoot.tsx
packages/react/src/dialog/root/DialogRootContext.ts
packages/react/src/dialog/utils/DialogContext.ts

Fixes https://github.com/mui/base-ui/issues/1165
The idea is to use common context between all dialog components. I extracted only the common things inside this context.

[Dialog, AlertDialog] Fix the nesting of different dialogs

---

packages/react/src/scroll-area/root/ScrollAreaRootContext.ts
packages/react/src/scroll-area/root/useScrollAreaRoot.ts
packages/react/src/scroll-area/scrollbar/ScrollAreaScrollbar.test.tsx
packages/react/src/scroll-area/scrollbar/ScrollAreaScrollbar.tsx
packages/react/src/scroll-area/thumb/ScrollAreaThumb.tsx
packages/react/src/scroll-area/viewport/useScrollAreaViewport.tsx

Closes #982
Previously both scrollbars received `data-scrolling` even if the orientation of the scroll was for the other scrollbar. This splits the states so they time out independently.

[ScrollArea] Differentiate `x`/`y` orientation `data-scrolling`

---

docs/src/components/QuickNav/QuickNav.tsx

Avoid back and forth quick nav positioning updates when:
- Rounding errors occur due to zoom / pinch-zoom
- Current position can be either sticky or non-sticky without any difference
- Bouncing back from overscroll

[docs] Sturdier quick nav math

---

docs/src/syntax-highlighting/index.mjs

Closes #1211. Not sure what this is for but it's breaking the code blocks.

[docs] Remove `rehypeEmptyLines`

---

packages/react/src/popover/trigger/PopoverTrigger.tsx
packages/react/src/tooltip/trigger/TooltipTrigger.tsx

[Popover, Tooltip] Fix PopoverTrigger and TooltipTrigger prop types

---

docs/src/app/(public)/(content)/react/overview/about/page.mdx

I guess to be coherent with? https://github.com/mui/base-ui/blob/74a3d083b3e63224bee11f7b3d01ab558a4082b2/README.md?plain=1#L3
Also, if we are playing the game of previous projects, I imagine we should add fluent ui https://github.com/microsoft/fluentui/pulls?q=is%3Apr+author%3Amnajdova+is%3Aclosed (one of the two repos).

[docs] Rename MUI -> Material UI

---

packages/react/src/tooltip/trigger/TooltipTrigger.spec.tsx
packages/react/src/tooltip/trigger/TooltipTrigger.tsx
packages/react/src/utils/types.ts

Continues #1209
Switches to `GenericHTMLProps` for the `render` props type. This includes the `ref` which was previously missing. Using `'div'` for Tooltip uses the `GenericHTMLProps` regardless.

[core] Fix render prop types

---

prettier.config.js

Avoid duplication, so we can have more of a shared baseline.
**Off-topic.** We will likely need to change how `@mui/monorepo/prettier.config` is handled and where the source is located, but duplication and best location are separate problems, e.g. mui/material-ui also has Tailwind CSS in its repo, it should have the plugin too.

[core] Rely more on baseline prettier config

---

packages/react/src/alert-dialog/popup/AlertDialogPopup.tsx
packages/react/src/dialog/popup/DialogPopup.tsx
packages/react/src/menu/positioner/MenuPositioner.tsx
packages/react/src/select/positioner/SelectPositioner.tsx
packages/react/src/utils/InternalBackdrop.tsx

This solves the flicker on the trigger due to the new internal backdrop without needing to change when `[data-popup-open]` is removed.
Before:
https://github.com/user-attachments/assets/9d83ea26-e5b1-4015-8921-c71d2120673f
After: 
https://github.com/user-attachments/assets/0df0dee2-2765-4c11-ba77-fa5d17f834d7

[Dialog, Menu, Select] Set `pointer-events` on `InternalBackdrop` based on `open` state

---

README.md
docs/src/app/(public)/(content)/react/overview/about/page.mdx
docs/src/app/(public)/page.tsx

Fix https://base-ui.com/react/overview/about
While I was at it, I thought It would sync the team section to be the same between README visible on npm page and docs.

[docs] Fix line break for Floating UI brand name

---

docs/src/app/not-found.tsx

I guess it makes a bit more sense to start from the first page of the docs when hitting a 404? it could also help better appreciate traffic on the docs pages to know where we should allocate more time.

[docs] Have 404 link points to first page of docs

---

packages/react/.npmignore
packages/react/package.json

Exclude the *.tsbuildinfo files from the published package. These files are meant to be used internally to speed up typechecking and have no use in distributed packages, increasing their weight unnecessarily.

[core] Remove tsbuildinfo from the built package

---

SECURITY.md

Today, https://github.com/mui/base-ui/security/policy has the content of https://github.com/mui/.github/blob/master/SECURITY.md. It seems that it would be better to add something custom.

[docs] Add security coverage

---

packages/react/src/slider/indicator/useSliderIndicator.ts

Removing `position: absolute` from `Indicator` makes range slider built-in styles look broken: https://codesandbox.io/p/sandbox/quiet-cache-mcf3cr

[Slider] Set `position: relative` on range slider indicator

---

packages/react/src/preview-card/portal/PreviewCardPortal.tsx
packages/react/src/tooltip/portal/TooltipPortal.tsx
packages/react/src/utils/FloatingPortalLite.tsx

Part of #1246. Depends on refactors made in #1222
This prevents bringing in tabbable logic (`tabbable` dependency and extra code from Floating UI) if just importing the `Tooltip` or `PreviewCard` components, saving bundle size

[Tooltip, PreviewCard] Use `FloatingPortalLite`

---

packages/react/src/number-field/decrement/NumberFieldDecrement.test.tsx
packages/react/src/number-field/increment/NumberFieldIncrement.test.tsx
packages/react/src/number-field/root/useNumberFieldRoot.ts

Closes #1287
The issue is `onMouseEnter` fires once on touch on focus, which allows quick touches to work but only the first time. After that, taps within `TOUCH_TIMEOUT` (50ms, `touchend`) don't activate the button. To solve this we can conditionally determine if `onClick` can activate by checking if the auto change already started after the timeout, which only applies to touch

[NumberField] Correctly handle quick touches

---

packages/react/src/utils/useTransitionStatus.ts

Removed a prop from the JSDocs that is no longer used in the hook.

[core] Fix wrong JSDocs in `useTransitionStatus`

---

.github/ISSUE_TEMPLATE/3.get-help.md
docs/public/_redirects
docs/src/app/(public)/(content)/react/overview/about/page.mdx

The value of this change:
- Makes the link we share on socials, etc. feel more official, and clean
- Make it easy in case Discord changes the invitation URL (unlikely to happen)
Also, once we reach level 3 of the boost in Discord, we can have plain text invitation URLs from Discord.
---
**Off-topic**. As long as Base UI userbase is small, directing users to Discord for support can be interesting, we have the same strategy with Toolpad, it helps go in depth in the user feedback.
However, after some level of scale (volume of questions), I believe it's really important that we move all support off of it, instead to GitHub issues + Stack Overflow; and only use Discord for community bounding like in https://mui.com/material-ui/getting-started/support/#discord. The reason is searchability, …

[docs] Use discord redirect

---

docs/reference/generated/menu-radio-group.json
packages/react/src/accordion/root/useAccordionRoot.ts
packages/react/src/collapsible/trigger/useCollapsibleTrigger.ts
packages/react/src/menu/checkbox-item/MenuCheckboxItem.test.tsx
packages/react/src/menu/item/MenuItem.test.tsx
packages/react/src/menu/radio-group/MenuRadioGroup.tsx
packages/react/src/menu/radio-group/MenuRadioGroupContext.ts
packages/react/src/menu/radio-item/MenuRadioItem.test.tsx
packages/react/src/menu/radio-item/MenuRadioItem.tsx
packages/react/src/menu/trigger/useMenuTrigger.ts
packages/react/src/select/item/SelectItem.test.tsx
packages/react/src/select/item/useSelectItem.ts
packages/react/src/select/root/useSelectRoot.ts
packages/react/src/select/trigger/SelectTrigger.test.tsx
packages/react/src/select/trigger/SelectTrigger.tsx
packages/react/src/select/trigger/useSelectTrigger.ts
packages/react/src/use-button/useButton.test.tsx
packages/react/src/use-button/useButton.ts

Using `mergeReactProps`, our event handlers can't (easily) prevent external handlers since external ones are called first, it seems best to just bypass mergeReactProps here and manually call the external `onClick`.
Additionally found these issues along the way and fixed them:
- `<Menu.RadioGroup disabled />` didn't work
- `<Select.Trigger disabled />` didn't work
Closes https://github.com/mui/base-ui/issues/1312

[useButton] Fix `focusableWhenDisabled` components

---

CHANGELOG.md
docs/src/app/(public)/(content)/react/overview/releases/page.mdx
docs/src/syntax-highlighting/index.css
package.json
packages/react/package.json

Pending https://github.com/mui/base-ui/pull/1313 before merge

[release] v1.0.0-alpha.5

---

packages/react/src/alert-dialog/description/AlertDialogDescription.tsx
packages/react/src/alert-dialog/root/AlertDialogRoot.test.tsx
packages/react/src/alert-dialog/title/AlertDialogTitle.tsx
packages/react/src/dialog/description/DialogDescription.tsx
packages/react/src/dialog/root/DialogRoot.test.tsx
packages/react/src/dialog/title/DialogTitle.tsx

Fixes https://github.com/mui/base-ui/issues/1325

[Dialogs] Fix missing `id`s on Title and Description

---

docs/src/app/(public)/(content)/react/components/tabs/demos/hero/css-modules/index.tsx
docs/src/app/(public)/(content)/react/components/tabs/demos/hero/tailwind/index.tsx

[Tabs examples](https://base-ui.com/react/components/tabs) are incorrectly named as `ExampleScrollArea`.

[docs][Tabs] Fix example component names

---

packages/react/src/alert-dialog/backdrop/AlertDialogBackdrop.tsx
packages/react/src/alert-dialog/popup/AlertDialogPopup.tsx
packages/react/src/alert-dialog/root/AlertDialogRoot.test.tsx
packages/react/src/dialog/backdrop/DialogBackdrop.tsx
packages/react/src/dialog/popup/DialogPopup.test.tsx
packages/react/src/dialog/popup/DialogPopup.tsx
packages/react/src/dialog/root/DialogRoot.test.tsx
packages/react/src/dialog/root/useDialogRoot.ts
packages/react/src/utils/InternalBackdrop.tsx

This detects if the click occurred on the dialog's owning backdrop. This ensures dialogs that opened previously but aren't nested in the React tree won't close. This fixes bugs related to multiple "unrelated" dialogs that open independently without using any kind of Provider.
Note: non-nested dialogs don't support CSS variables or limiting to only one (topmost) backdrop as that requires context/React tree nesting. I figure that feature is usually useful for closely related dialogs that will be nested in the React tree anyway.
Closes #1320

[Dialogs] Support multiple non-nested modal backdrops

---

test/e2e/TestViewer.tsx
test/e2e/main.tsx
test/regressions/TestViewer.tsx
test/regressions/main.tsx

Ported https://github.com/mui/material-ui/pull/44935: removed `React.Suspense` from around tests and mocked clock.

[test] Speed up regression and E2E tests

---

.circleci/config.yml

npmjs.org rotated the public signing keys but corepack hardcoded the old one, causing all the CI pipelines to fail ([example](https://app.circleci.com/pipelines/github/mui/base-ui/7353/workflows/1865f9ae-7da2-41ab-ac41-27acd7c04f19/jobs/65711)) because it couldn't install pnpm properly: https://github.com/nodejs/corepack/issues/612
This fix fetches the latest keys and storing them in an env variable, taken from this comment: https://github.com/nodejs/corepack/issues/612#issuecomment-2629911771
The alternatives are not as good:
- `npm install -g corepack@latest` will work but requires `sudo` in CircleCI which is annoying to install
- `COREPACK_INTEGRITY_KEYS=0` disable the signature check, risky!

[core] Fix corepack installation in CircleCI

---

packages/react/src/checkbox-group/useCheckboxGroupParent.ts
packages/react/src/checkbox/root/useCheckboxRoot.ts
packages/react/src/field/root/FieldRoot.tsx
packages/react/src/form/Form.tsx
packages/react/src/menu/radio-group/MenuRadioGroup.tsx
packages/react/src/number-field/root/useNumberFieldRoot.ts
packages/react/src/popover/root/usePopoverRoot.ts
packages/react/src/preview-card/root/usePreviewCardRoot.ts
packages/react/src/switch/root/useSwitchRoot.ts
packages/react/src/tooltip/root/useTooltipRoot.ts
packages/react/src/utils/useEventCallback.ts

Avoids needing to pass an empty NOOP function to `useEventCallback` for optional function props

[core] Allow undefined function for `useEventCallback`

---

packages/react/src/slider/control/SliderControl.test.tsx
packages/react/src/slider/control/SliderControl.tsx
packages/react/src/slider/control/useSliderControl.ts
packages/react/src/slider/indicator/SliderIndicator.test.tsx
packages/react/src/slider/root/useSliderRoot.ts
packages/react/src/slider/thumb/SliderThumb.test.tsx
packages/react/src/slider/track/SliderTrack.test.tsx
packages/react/src/slider/value/SliderValue.test.tsx

Fixes https://github.com/mui/base-ui/issues/1360
Fixes https://github.com/mui/base-ui/issues/1406
**Demo:** https://stackblitz.com/edit/vitejs-vite-zsatgbgk?file=src%2FApp.tsx
The demo shows both fixes:
- when setting the value with the NumberField, the corresponding slider should reposition correctly
- when dragging a thumb to match the same value set by a NumberField (of an adjacent row) the thumbs should line up exactly and have the same CSS `width` value

[Slider] Fix thumb positioning

---

packages/react/src/index.ts

Thank you for the `alpha.6 ` release, just noticed that `Avatar` was missing from the main export when testing it

[Avatar] Add missing Avatar export

---

babel.config.js
package.json
pnpm-lock.yaml

The `babel-plugin-instanbul` and Babel coverage config is not needed anymore as we use Vitest.

[core] Remove babel-plugin-istanbul

---

packages/react/src/utils/mergeReactProps.test.ts
packages/react/src/utils/mergeReactProps.ts

Fixed the `mergeReactProps` utility to handle event handlers that don't have the event as the first parameter. It now checks if the parameter is an object and contains the `nativeEvent` field before adding the `preventBaseUIHandler` method.
Additionally, I refactored the implementation to be more readable.
Fixes #1430

[core] Make `mergeReactProps` work with non-native event handlers

---

packages/react/src/avatar/image/AvatarImage.tsx
packages/react/src/avatar/image/useImageLoadingStatus.ts

Add crossOrigin Support to useImageLoadingStatus Hook. 
> This PR adds crossOrigin support to the useImageLoadingStatus hook to handle images hosted on external domains that require specific crossOrigin settings (anonymous or use-credentials).
> 
> By including this option, we ensure broader compatibility with external image sources and resolve potential loading issues.
Note: radix-ui/primitives(https://github.com/radix-ui/primitives) has this exact issue and already has a PR https://github.com/radix-ui/primitives/pull/3261. So here's a corresponding PR for Base UI 😊

[Avatar] Support cross origin in useImageLoadingStatus

---

packages/react/src/field/root/FieldRoot.test.tsx

The FieldRoot tests verifying Select are flaky when run on a fast machine using browser mode. Adding an artificial delay after a trigger is pressed does also seem to help, but it further increases the duration of the test. Since they work fine in JSDOM, I opted for skipping them in browsers.

[test] Skip flaky FieldRoot tests in real browsers

---

packages/react/src/radio-group/RadioGroup.test.tsx
packages/react/src/radio-group/useRadioGroup.ts

1. The `name` prop wasn't being forwarded from `Field` to `RadioGroup` `<input>`
2. The `required` prop wasn't being forwarded from `RadioGroup` to `<input>`, and native HTML validation requires it be visually hidden, not true `type=hidden`
Part of #1425, mentioned in https://github.com/mui/base-ui/pull/1053/#discussion_r1942478141

[RadioGroup] Fix `Form`/`Field` validation integration

---

packages/react/src/collapsible/root/CollapsibleRoot.test.tsx
packages/react/src/collapsible/trigger/CollapsibleTrigger.tsx

[Collapsible] Update props destructuring to fix Trigger disabled state

---

docs/reference/generated/alert-dialog-close.json
docs/reference/generated/alert-dialog-trigger.json
docs/reference/generated/dialog-close.json
docs/reference/generated/dialog-trigger.json
packages/react/src/alert-dialog/close/AlertDialogClose.test.tsx
packages/react/src/alert-dialog/close/AlertDialogClose.tsx
packages/react/src/alert-dialog/close/AlertDialogCloseDataAttributes.ts
packages/react/src/alert-dialog/trigger/AlertDialogTrigger.test.tsx
packages/react/src/alert-dialog/trigger/AlertDialogTrigger.tsx
packages/react/src/alert-dialog/trigger/AlertDialogTriggerDataAttributes.ts
packages/react/src/dialog/close/DialogClose.test.tsx
packages/react/src/dialog/close/DialogClose.tsx
packages/react/src/dialog/close/DialogCloseDataAttributes.ts
packages/react/src/dialog/close/useDialogClose.ts
packages/react/src/dialog/trigger/DialogTrigger.test.tsx
packages/react/src/dialog/trigger/DialogTrigger.tsx
packages/react/src/dialog/trigger/DialogTriggerDataAttributes.ts
packages/react/src/popover/trigger/PopoverTrigger.test.tsx
packages/react/src/popover/trigger/PopoverTrigger.tsx

Closes https://github.com/mui/base-ui/issues/1470
Demo: https://codesandbox.io/p/devbox/suspicious-bessie-khdjkj?file=%2Fsrc%2FApp.tsx%3A8%2C1
Use useButton internally in (Alert)Dialog.Trigger, (Alert)Dialog.Close, Popover.Trigger to fix their disabled states:
- always sets `data-disabled` when disabled for consistency, even when it's a native `button` element
- when a non-interactive element (e.g. a span) is rendered, functionality is disabled accordingly and `aria-disabled` is used instead of the HTML `disabled` attribute

[AlertDialog][Dialog][Popover] Fix non-interactive button disabled state

---

packages/react/src/accordion/header/AccordionHeader.tsx
packages/react/src/accordion/item/AccordionItem.tsx
packages/react/src/accordion/panel/AccordionPanel.tsx
packages/react/src/accordion/root/AccordionRoot.tsx
packages/react/src/avatar/fallback/AvatarFallback.tsx
packages/react/src/avatar/image/AvatarImage.tsx
packages/react/src/avatar/root/AvatarRoot.tsx
packages/react/src/checkbox-group/CheckboxGroupContext.ts
packages/react/src/checkbox-group/useCheckboxGroup.tsx
packages/react/src/checkbox-group/useCheckboxGroupParent.ts
packages/react/src/checkbox/root/CheckboxRoot.tsx
packages/react/src/checkbox/root/useCheckboxRoot.ts
packages/react/src/collapsible/root/CollapsibleRoot.tsx
packages/react/src/number-field/root/NumberFieldRoot.tsx
packages/react/src/number-field/root/NumberFieldRootContext.ts
packages/react/src/number-field/root/useNumberFieldRoot.ts
packages/react/src/number-field/root/useScrub.ts
packages/react/src/slider/control/SliderControl.tsx
packages/react/src/slider/indicator/SliderIndicator.tsx
packages/react/src/slider/root/SliderRoot.tsx
packages/react/src/slider/thumb/SliderThumb.tsx
packages/react/src/slider/track/SliderTrack.tsx
packages/react/src/slider/value/SliderValue.tsx
packages/react/src/toggle-group/ToggleGroup.tsx
packages/react/src/toggle-group/useToggleGroup.ts
packages/react/src/toggle/Toggle.tsx

While evaluating [API Extractor](https://api-extractor.com/) I noticed inconsistencies in how some of our namespaces are exported:
- there are redundant `export`s making API Explorer crash
- there are namespaces named differently to components/hooks (with differing casing).
This PR solves both of these issues.

[core] Export namespaces consistently

---

packages/react/src/slider/root/useSliderRoot.ts

Fixes https://github.com/mui/base-ui/issues/1471
Log a console warning when `min` is not less than `max` and don't update the state. When min/max are the same something divides by zero internally and causes a loop.

[Slider] Warn when `min` is not less than `max`

---

docs/src/app/(public)/(content)/react/handbook/animation/page.mdx
packages/react/src/alert-dialog/root/AlertDialogRoot.test.tsx
packages/react/src/dialog/root/DialogRoot.test.tsx
packages/react/src/menu/root/MenuRoot.test.tsx
packages/react/src/popover/root/PopoverRoot.test.tsx
packages/react/src/preview-card/root/PreviewCardRoot.test.tsx
packages/react/src/select/root/SelectRoot.test.tsx
packages/react/src/tooltip/root/TooltipRoot.test.tsx

Tested this in the browser and saw no issues after a couple minutes of testing - not sure why it flakes randomly
Also fixed stale `action` prop naming in the code

[test] Fix PreviewCard test flake

---

packages/react/src/composite/list/CompositeList.tsx

Matches https://github.com/floating-ui/floating-ui/pull/3210

[Composite] Derive sorted map state

---

docs/src/app/(public)/page.tsx

Fix #1163
This still didn't change:
It feels off. The solution is to apply the instructions of https://developers.google.com/search/docs/appearance/site-names#json-ld.
That seems correct: https://validator.schema.org/#url=https%3A%2F%2Fdeploy-preview-1520--base-ui.netlify.app%2F. We should see after a couple of days:
---
**Off-topic**: the URL is truncated, but a path like this:
would be clearer. Opened an umbrella issue for SEO: .

[docs] Fix SEO site name description

---

packages/react/src/slider/control/SliderControl.test.tsx
packages/react/src/slider/indicator/SliderIndicator.test.tsx
packages/react/src/slider/root/SliderRoot.test.tsx
packages/react/src/slider/root/SliderRoot.tsx
packages/react/src/slider/root/useSliderRoot.ts
packages/react/src/slider/thumb/SliderThumb.test.tsx
packages/react/src/slider/thumb/useSliderThumb.ts
packages/react/src/slider/track/SliderTrack.test.tsx
packages/react/src/slider/value/SliderValue.test.tsx

Before: https://codesandbox.io/p/sandbox/ancient-sunset-v4kx8d
After: https://codesandbox.io/p/devbox/bold-visvesvaraya-7vsy9w
The % values should be clamped before updating the state to prevent the thumb/indicator from ever going out of bounds.
Fixes https://github.com/mui/base-ui/issues/1423

[Slider] Fix thumb positioning when controlled value violates min/max/step

---

docs/src/app/(public)/(content)/react/utils/use-render/demos/render-callback/css-modules/index.tsx
docs/src/app/(public)/(content)/react/utils/use-render/demos/render/css-modules/index.tsx
docs/src/app/(public)/(content)/react/utils/use-render/page.mdx
docs/src/components/ReferenceTable/PropsReferenceTable.tsx
packages/react/src/alert-dialog/popup/AlertDialogPopup.tsx
packages/react/src/collapsible/panel/useCollapsiblePanel.ts
packages/react/src/collapsible/trigger/useCollapsibleTrigger.ts
packages/react/src/dialog/popup/DialogPopup.tsx
packages/react/src/dialog/popup/useDialogPopup.tsx
packages/react/src/dialog/root/useDialogRoot.ts
packages/react/src/field/control/useFieldControlValidation.ts
packages/react/src/fieldset/root/FieldsetRoot.tsx
packages/react/src/merge-props/mergeProps.test.ts
packages/react/src/merge-props/mergeProps.ts
packages/react/src/popover/root/usePopoverRoot.ts
packages/react/src/select/icon/SelectIcon.tsx
packages/react/src/slider/indicator/useSliderIndicator.ts
packages/react/src/slider/thumb/useSliderThumb.ts
packages/react/src/slider/value/useSliderValue.ts
packages/react/src/tabs/panel/useTabsPanel.ts
packages/react/src/use-button/useButton.ts
packages/react/src/use-render/useRender.ts
packages/react/src/utils/useComponentRenderer.ts

This is a continuation of #1418.
Docs: https://deploy-preview-1551--base-ui.netlify.app/react/utils/use-render
APIs refined:
1. `useRender.ElementProps` becomes `useRender.ComponentProps`. Since it's used for _components_ and has a special `render` prop, it doesn't make sense to use the word `Element`
2. `mergeProps.Props` -> `useRender.ElementProps`. These are raw element props, and it's confusing to have a namespace on `mergeProps` and two separate things to remember. We might as well reuse `useRender` for this purpose.
3. ~`mergeProps` defaults to `'div'` tag to get type inference out of the box for the most common case (I'm not sold on this being a good default, but it's easy to forget adding a tag and losing inference and types)~
4. Small tweaks to utility naming
5. Docs improvements

[useRender] Refine docs and APIs

---

packages/react/src/field/control/useFieldControl.ts
packages/react/src/field/root/FieldRoot.test.tsx

Previously, `FieldControl` only checked if the value exists on mount and `onChange`, but not when the `value` prop is changed externally

[Field] Fix `FieldControl` [data-filled] not reacting to external value changes

---

packages/react/src/number-field/root/NumberFieldRoot.test.tsx
packages/react/src/number-field/root/useNumberFieldRoot.ts
packages/react/src/number-field/scrub-area-cursor/NumberFieldScrubAreaCursor.test.tsx
packages/react/src/number-field/utils/parse.ts

Certain locales define space as a thousands separator in numbers. The NumberField incorrectly parsed numbers from these locales. If a thousands separator is a space-like character (including non-breaking  and different width spaces), we treat every space-like character as a possible separator.
Fixes https://github.com/mui/base-ui/issues/1576

[NumberField] Fix parse of numbers with spaces as thousands separators

---

packages/react/src/alert-dialog/popup/AlertDialogPopup.tsx
packages/react/src/alert-dialog/trigger/AlertDialogTrigger.tsx
packages/react/src/dialog/popup/DialogPopup.tsx
packages/react/src/dialog/trigger/DialogTrigger.tsx
packages/react/src/menu/positioner/MenuPositioner.tsx
packages/react/src/menu/trigger/MenuTrigger.test.tsx
packages/react/src/menu/trigger/MenuTrigger.tsx
packages/react/src/popover/positioner/PopoverPositioner.tsx
packages/react/src/popover/trigger/PopoverTrigger.test.tsx
packages/react/src/popover/trigger/PopoverTrigger.tsx
packages/react/src/select/positioner/SelectPositioner.tsx
packages/react/src/select/trigger/SelectTrigger.tsx
packages/react/src/utils/InternalBackdrop.tsx

This was reported on Discord and is worse on Firefox. When simply pressing outside (with a hard click on a trackpad) it selects the document's text unexpectedly. 
The internal backdrop `pointer-events: none` style seems to cause the bug while closing on FF & Safari; `modal={false}` is the current workaround since it avoids rendering the backdrop
In order to maintain the fix in https://github.com/mui/base-ui/pull/1221, I changed the style hook for `[data-popup-open]` to match the `mounted` state to prevent the flicker instead. It doesn't map 1:1 with the `open` state, but I'm not sure if that matters here since in practice you want it kept when mounted, not open

[popups] Fix selection on outside press on Firefox with modal prop

---

packages/react/src/number-field/input/NumberFieldInput.tsx
packages/react/src/number-field/root/NumberFieldRoot.test.tsx
packages/react/src/number-field/root/NumberFieldRoot.tsx
packages/react/src/number-field/root/useNumberFieldButton.ts
packages/react/src/number-field/root/useNumberFieldRoot.ts
packages/react/src/number-field/root/useScrub.ts
packages/react/src/number-field/utils/types.ts

Replaces the global listeners by checking for `event.shfitKey/altKey` on the event if available. 
The only times it's not available on the event is when pressing and holding the increment button and then pressing shift midway through, but I don't consider that to be very important/relevant
Fixes #1064

[NumberField] Fix `large/smallStep` getting stuck

---

packages/react/src/number-field/root/useScrub.ts

There should be no WebKit check for pointerup release. After the promise changes, Safari no longer cancels scrubbing.

[NumberField] Fix ScrubArea on Safari

---

packages/react/src/collapsible/trigger/useCollapsibleTrigger.ts
packages/react/src/tabs/tab/useTabsTab.ts
packages/react/src/toggle/useToggle.ts
packages/react/src/toolbar/button/ToolbarButton.tsx
packages/react/src/use-button/useButton.test.tsx
packages/react/src/use-button/useButton.ts

I found an issue with the [Close confirmation](https://base-ui.com/react/components/dialog#close-confirmation) example which has a `<form>` wrapper, where the close button now uses the default `submit` type. 
There seemed to be a regression (likely due to the prop merging changes) that causes the `type` of the default button renderer function to be overridden with `undefined` type from `useButton`, so now it's a submit button incorrectly.
The hook specifies `'button'` as the default type in jsdoc but not in the runtime code. As far as I can tell, we have no submit button component anywhere for this not to be the default

[useButton] Default to `'button'` type

---

docs/next.config.mjs

I noticed the current config option has been deprecated

[core] Disable NextJS dev mode build indicator

---

packages/react/src/slider/root/useSliderRoot.ts
packages/react/src/slider/thumb/SliderThumb.test.tsx

Fixes https://github.com/mui/base-ui/issues/1602
Demo: https://codesandbox.io/p/sandbox/great-wu-p6trjf
The issue was that `percentageValues` which determines the positioning also need to be clamped with adjacent values in range sliders like the value itself

[Slider] Prevent range slider thumbs from being dragged past each other

---

docs/src/blocks/GoogleAnalytics.tsx

I'm preparing the monthly meeting, I wanted to review GA stats on Base UI, I was curious to asses how simularweb data is accurate vs. not (helpful to know how much to rely on it) and to check the difference of screen pixel density in base-ui.com vs. mui.com.
GA today simply doesn't work on base-ui.com. There are probably more to make it work, but this is a quick win, to go back to how mui.com is correctly configured. https://app.netlify.com/sites/base-ui/metrics/analytics is also an option but seems limited to 30 days, not good enough.
before https://deploy-preview-1666--base-ui.netlify.app/
after https://deploy-preview-1667--base-ui.netlify.app/
---
**Off topic**. Code owners now seem to spam a bit.

[docs-infra] Fix GA4 configuration

---

packages/react/src/alert-dialog/popup/AlertDialogPopup.tsx
packages/react/src/alert-dialog/trigger/AlertDialogTrigger.tsx
packages/react/src/dialog/popup/DialogPopup.tsx
packages/react/src/dialog/trigger/DialogTrigger.tsx
packages/react/src/menu/trigger/MenuTrigger.tsx
packages/react/src/popover/trigger/PopoverTrigger.tsx
packages/react/src/select/positioner/SelectPositioner.tsx
packages/react/src/select/trigger/SelectTrigger.tsx

The real `inert` attribute [prevents the selection issue on Firefox](https://github.com/mui/base-ui/pull/1573) while still allowing `[data-popup-open]` to map to `open` instead of `mounted` like before, which looks better for transitions

[popups] Use consistent `inert` attr and map `[data-popup-open]` back to `open`

---

packages/react/src/number-field/utils/parse.test.ts
packages/react/src/number-field/utils/parse.ts

Fixes #1675
When `style: "percent"`, it's expected that the number is divided by 100 (0.1 = 10%, etc.)
When `style: "unit"`, then the percent is not divided, so 40 = 40%.
https://codesandbox.io/p/sandbox/base-ui-cra-ts-forked-7xzgdc?file=%2Fsrc%2FApp.tsx

[NumberField] Correct percentage parse handling

---

packages/react/src/use-button/useButton.test.tsx
packages/react/src/use-button/useButton.ts

`<div type="button">` became a default after #1594

[useButton] Avoid applying type attribute to non-button tags

---

packages/react/src/radio-group/RadioGroup.test.tsx
packages/react/src/radio-group/RadioGroup.tsx
packages/react/src/radio/root/RadioRoot.test.tsx
packages/react/src/radio/root/RadioRoot.tsx
packages/react/src/radio/root/useRadioRoot.tsx

[Radio] Fix value forwarding and null handling

---

packages/react/src/alert-dialog/popup/AlertDialogPopup.tsx
packages/react/src/alert-dialog/root/AlertDialogRoot.test.tsx
packages/react/src/dialog/popup/DialogPopup.tsx
packages/react/src/dialog/popup/useDialogPopup.tsx
packages/react/test/popupConformanceTests.tsx

Adds tests for https://github.com/mui/base-ui/issues/1552
The underlying issue is fixed in floating-ui

[test] Add more conformance tests for popups

---

.codesandbox/template/public/index.html
docs/public/static/favicon-dev.svg
docs/public/static/favicon.svg
docs/src/app/Favicons.tsx

Having some fun.
Before: https://deploy-preview-1715--base-ui.netlify.app/
After: https://deploy-preview-1717--base-ui.netlify.app/
I'm not 100% sure about the experience, but that do seem better.
Context: https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs

[docs] Improve favicon dark mode

---

packages/react/src/slider/root/useSliderRoot.ts
packages/react/src/slider/thumb/useSliderThumb.ts

Fixes https://github.com/mui/base-ui/issues/1731
Demo: https://codesandbox.io/p/sandbox/fast-glitter-7tck3z
When 2 or more thumbs overlap in the same position they can be dragged apart now

[Slider] Fix overlapping slider thumbs stuck at min or max

---

docs/src/components/ReferenceTable/PropsReferenceTable.tsx

Fixes #1742. There's other props like `id` as well

[docs] Disable infotip for empty prop descriptions

---

docs/src/app/(public)/(content)/react/components/scroll-area/page.mdx

`ScrollArea.Content` was not displayed in the docs.

[ScrollArea] Display Content part in docs

---

docs/reference/generated/toast-root.json
scripts/api-docs-builder/src/formatter.ts

Fixed how arrays of complex types are displayed in the docs
Before:
After:
Preview: https://deploy-preview-1765--base-ui.netlify.app/react/components/toast#root
Related to #1754

[docs] Fix formatting of arrays in API reference

---

docs/reference/generated/select-root.json
packages/react/src/select/root/useSelectRoot.ts

This type shouldn't exist on `Select.Root` and is unused

[docs][Select] Remove `transitionStatus` prop from `Select.Root` docs

---

packages/react/src/checkbox/root/CheckboxRoot.test.tsx
packages/react/src/checkbox/root/CheckboxRoot.tsx
packages/react/src/checkbox/root/useCheckboxRoot.ts

Closes https://github.com/mui/base-ui/issues/1775
- Sets `aria-required="true"` when required (matches Radio)
- CheckboxRoot internally uses `useButton` https://github.com/mui/base-ui/issues/1712

[Checkbox] Set `aria-required`, use `useButton`

---

packages/react/src/field/label/useFieldLabel.ts

- Clicking `Field.Label` multiple times ensures focus can stay on a `NumberField.Input`
- Closes #586

[Field] Improve `Label` logic that prevents text selection on double click

---

packages/react/src/field/control/useFieldControlValidation.ts
packages/react/src/field/root/FieldRoot.test.tsx

Fixes #1778 
- For `valueMissing`, require that the input have been dirtied at some point to produce an error on blur. This reduces errors for empty fields to begin with
- For any other error, it always produces an error on blur even if not dirtied yet

[Field] Fix validation inconsistency

---

.circleci/config.yml
babel.config.js
pnpm-lock.yaml
pnpm-workspace.yaml
test/node-resolution/index.mjs
test/node-resolution/package.json

File extensions were broken since https://github.com/mui/base-ui/pull/1662. I believe the alias is only there in core to serve the mocha tests. we should never alias in babel.
To do:

[code-infra] Remove babel alias and fix extensions

---

package.json

I was trying to understand why the visual regression tests work correctly in Base UI but are broken in MUI X. Turns out, we didn't correctly copy Base UI in MUI X https://github.com/mui/mui-x/pull/17564. But also, turns out, that Base UI rely on the default port of Vite to not change (https://www.reddit.com/r/programming/comments/xh1vyr/fun_fact_vites_default_port_is_5173_which_spells/) for this to work. Since we might want to scope the port per project, not be dependent on the default port, and help debug, it seems best to explicitly specify the value.

[core] Set default regression port

---

packages/react/src/toast/root/ToastRoot.test.tsx
packages/react/src/toast/root/useToastRoot.ts

On iOS, the `pointermove` doesn't start firing until swiping ~10px after `pointerdown`. This led to a glitchy jump after swiping past that threshold, which was mentioned by @colmtuite. But the solution to fix this is quite straightforward (as commented), the swipe movement is adjusted from when it starts moving, not where the finger is after swiping

[Toast] Fix swipe jump on iOS

---

docs/src/app/(public)/(content)/react/components/accordion/page.mdx
docs/src/app/(public)/(content)/react/components/alert-dialog/page.mdx
docs/src/app/(public)/(content)/react/components/avatar/page.mdx
docs/src/app/(public)/(content)/react/components/checkbox-group/page.mdx
docs/src/app/(public)/(content)/react/components/checkbox/page.mdx
docs/src/app/(public)/(content)/react/components/collapsible/page.mdx
docs/src/app/(public)/(content)/react/components/dialog/page.mdx
docs/src/app/(public)/(content)/react/components/field/page.mdx
docs/src/app/(public)/(content)/react/components/fieldset/page.mdx
docs/src/app/(public)/(content)/react/components/form/page.mdx
docs/src/app/(public)/(content)/react/components/input/page.mdx
docs/src/app/(public)/(content)/react/components/menu/page.mdx
docs/src/app/(public)/(content)/react/components/meter/page.mdx
docs/src/app/(public)/(content)/react/components/number-field/page.mdx
docs/src/app/(public)/(content)/react/components/popover/page.mdx
docs/src/app/(public)/(content)/react/components/preview-card/page.mdx
docs/src/app/(public)/(content)/react/components/progress/page.mdx
docs/src/app/(public)/(content)/react/components/radio/page.mdx
docs/src/app/(public)/(content)/react/components/scroll-area/page.mdx
docs/src/app/(public)/(content)/react/components/select/page.mdx
docs/src/app/(public)/(content)/react/components/separator/page.mdx
docs/src/app/(public)/(content)/react/components/slider/page.mdx
docs/src/app/(public)/(content)/react/components/switch/page.mdx
docs/src/app/(public)/(content)/react/components/tabs/page.mdx
docs/src/app/(public)/(content)/react/components/toast/page.mdx
docs/src/app/(public)/(content)/react/components/toggle-group/page.mdx
docs/src/app/(public)/(content)/react/components/toggle/page.mdx
docs/src/app/(public)/(content)/react/components/toolbar/page.mdx
docs/src/app/(public)/(content)/react/components/tooltip/page.mdx

Example: https://deploy-preview-1803--base-ui.netlify.app/react/components/field#anatomy
Closes https://github.com/mui/base-ui/issues/1799

[docs] Separate anatomy sections from API reference

---

docs/src/app/(public)/(content)/react/components/tabs/demos/hero/css-modules/index.module.css

In our docs the CSS modules demo was actually using Tailwind's `[hidden]:where(...)` rule to hide inactive panels, and `display: flex` on the panel has higher specificity than the UA `[hidden]` style
Fixes https://github.com/mui/base-ui/issues/1801

[docs][Tabs] Set `display: none` on panel hidden state for CSS modules

---

packages/react/src/form/Form.tsx

Closes #1068
This doesn't apply to `NumberField` since the caret should be at the end of the input when it's incrementing/decrementing, as selecting the entire field is obscuring. It also doesn't select `<textarea>` as preserving caret location may be important here
Also ensures that `errors` is defined for the Form `clear` function

[Form] Select inputs on focus

---

packages/react/src/field/control/useFieldControlValidation.ts
packages/react/src/field/error/FieldError.test.tsx
packages/react/src/field/root/FieldRoot.test.tsx

After #1779, we need to set the error field itself back to false as well to ignore it.

[field] Set `valueMissing` to false if only error and not dirtied

---

packages/react/src/popover/popup/PopoverPopup.tsx
packages/react/src/popover/root/PopoverRootContext.ts
packages/react/src/popover/root/usePopoverRoot.ts
packages/react/src/popover/trigger/PopoverTrigger.tsx
packages/react/src/select/popup/SelectPopup.tsx
packages/react/src/select/root/SelectRootContext.ts
packages/react/src/select/root/useSelectRoot.ts
packages/react/src/select/trigger/useSelectTrigger.ts
packages/react/src/tooltip/popup/TooltipPopup.tsx
packages/react/src/tooltip/root/TooltipRootContext.ts
packages/react/src/tooltip/root/useTooltipRoot.ts
packages/react/src/tooltip/trigger/TooltipTrigger.tsx

Doesn't affect Select specifically for release, but it's changed on main already.
Closes #1744

[Select][Popover][Tooltip] Avoid prop getters when merging props

---

scripts/api-docs-builder/src/formatter.ts

Makes the API reference generator respect the `@type` JSDoc annotation. When present, it will override the type extracted from the TS AST.
Usage: 
```ts
export interface Props {
/**
* @type (() => void)
*/
onFoo?: SomeVeryComplicatedTypeThatUsersShouldntCareAbout;
}
```

[docs-infra] Make it possible to override the displayed type in API reference

---

docs/reference/generated/tooltip-positioner.json
packages/react/src/tooltip/positioner/useTooltipPositioner.ts

[Tooltip] Remove `trackCursorAxis` type from `Positioner`

---

packages/react/src/accordion/root/AccordionRoot.tsx
packages/react/src/composite/composite.ts
packages/react/src/composite/root/useCompositeRoot.ts
packages/react/src/dialog/popup/useDialogPopup.tsx
packages/react/src/number-field/input/NumberFieldInput.tsx
packages/react/src/radio-group/RadioGroup.tsx
packages/react/src/slider/thumb/SliderThumb.tsx
packages/react/src/tabs/root/TabsRoot.test.tsx
packages/react/src/toggle-group/ToggleGroup.tsx
packages/react/src/toolbar/button/ToolbarButton.test.tsx
packages/react/src/toolbar/input/useToolbarInput.ts

Fixes #1759
Triggers preview: https://deploy-preview-1871--base-ui.netlify.app/experiments/toolbar/triggers
- Inside `Dialog`/`AlertDialog`, it prevents composite behavior from escaping itself. `Popover`/anything that doesn't trap focus or close when focus escapes it allows it
- Tabs and any other composite works inside a Dialog/Popover correctly

[composites] Stop event propagation

---

packages/react/src/menu/positioner/MenuPositioner.test.tsx
packages/react/src/popover/positioner/PopoverPositioner.test.tsx
packages/react/src/preview-card/positioner/PreviewCardPositioner.test.tsx
packages/react/src/select/positioner/SelectPositioner.test.tsx
packages/react/src/tooltip/positioner/TooltipPositioner.test.tsx

Related to https://github.com/mui/material-ui/pull/46108
There I've moved `describeSkipIf` to a deep import to fix a type clash, but `base-ui` uses vitest for everything, so you shouldn't need to use that shim.

[code-infra] Prefer `describe.skipIf` instead of `describeSkipIf` on tests

---

docs/reference/generated/slider-thumb.json
packages/react/src/slider/thumb/SliderThumb.tsx

We decided to only expose the `inputRef`: https://github.com/mui/base-ui/issues/1619
The `<input>` element's `id` is now the Thumb's id + `-input`

[slider] Drop `inputId` prop from Thumb

---

packages/react/src/utils/useScrollLock.ts

The current implementation is causing lots of reflows.
Test case: https://www.notion.so/mui-org/Menu-profiling-1eecbfe7b66080c9a810c82f2308f04d
The "menu click" portion highlighted below is the render-blocking JS that needs to run before the browser repaints. After these changes, floating-ui becomes an interesting optimization target as it's the next big render-blocking task.

[perf] Fix `useLockScroll` forced reflows

---

docs/reference/generated/use-render.json
docs/src/app/(public)/(content)/react/utils/use-render/demos/render-callback/css-modules/index.tsx
docs/src/app/(public)/(content)/react/utils/use-render/demos/render/css-modules/index.tsx
docs/src/app/(public)/(content)/react/utils/use-render/page.mdx
packages/react/src/use-render/useRender.test.tsx
packages/react/src/use-render/useRender.ts
packages/react/src/utils/useRenderElement.tsx

This is both perf/refactor. Make `useRender` match the `useRenderElement` API.

[core] Performance/refactor: `useRender`

---

packages/react/src/input/Input.tsx

Fixes #1951 
Also, with the new docs generator, there's no need to destructure props needlessly

[input] Extend `Field.Control.State`

---

packages/react/src/menu/trigger/useMenuTrigger.ts
packages/react/src/select/trigger/useSelectTrigger.ts
packages/react/src/use-button/useButton.test.tsx
packages/react/src/use-button/useButton.ts

Modern Safari allows buttons to receive focus upon click/mousedown if they have a tabIndex of `0`. This ensures the `:focus-visible` style won't appear once focus moves to a popup.
https://github.com/mui/base-ui/pull/1846#issuecomment-2887579218

[useButton] Default `tabIndex` to `0`

---

packages/react/src/tooltip/positioner/useTooltipPositioner.ts
packages/react/src/tooltip/root/TooltipRoot.test.tsx
packages/react/src/tooltip/root/TooltipRoot.tsx
packages/react/src/tooltip/root/TooltipRootContext.ts

[tooltip] Apply `pointer-events: none` to `Positioner` when not hoverable

---

packages/react/src/checkbox-group/CheckboxGroup.test.tsx
packages/react/src/checkbox/root/useCheckboxRoot.ts

Fixes https://github.com/mui/base-ui/issues/1950

[field][checkbox group] Fix `validate` fn incorrectly running twice

---

docs/reference/generated/use-render.json
packages/react/src/number-field/scrub-area-cursor/NumberFieldScrubAreaCursor.tsx
packages/react/src/radio/root/RadioRoot.tsx
packages/react/src/use-render/useRender.ts
packages/react/src/utils/useRenderElement.tsx
scripts/api-docs-builder/src/formatter.ts

Instead of using `useRenderElementLazy` which skips just a small part of processing when there's nothing to render, I introduced an `enabled` parameter to `useRenderElement`. It skips most of the logic (including prop merging).
There were some TS acrobatics necessary to ensure `useRenderElement` actually returns a `React.ReactElement` when enabled and `null` when disabled.

[performance] Skip most of useRenderElement logic when unnecessary

---

docs/reference/generated/context-menu-root.json
docs/reference/generated/menu-popup.json
docs/reference/generated/menu-root.json
packages/react/src/context-menu/root/ContextMenuRoot.tsx
packages/react/src/menu/popup/MenuPopup.test.tsx
packages/react/src/menu/popup/MenuPopup.tsx
packages/react/src/menu/root/MenuRoot.test.tsx
packages/react/src/menu/root/MenuRoot.tsx

Closes #1855
`closeDelay` was another prop missing that `Popover` and other hoverable ones have.

[menu] Add `finalFocus` and `closeDelay` props

---

packages/react/src/collapsible/root/useCollapsibleRoot.ts
packages/react/src/utils/useTransitionStatus.ts

Sandbox: https://codesandbox.io/p/sandbox/elastic-banzai-f44hrt
Fixes https://github.com/mui/base-ui/issues/1978
Adds a param to make the `'idle'` status optional

[core] Fix CSS transition interruptibility

---

docs/src/app/(private)/experiments/popups/popups-transform-origin.module.css
docs/src/app/(private)/experiments/popups/popups-transform-origin.tsx
packages/react/src/menu/positioner/MenuPositioner.tsx
packages/react/src/navigation-menu/positioner/NavigationMenuPositioner.tsx
packages/react/src/popover/positioner/PopoverPositioner.tsx
packages/react/src/preview-card/positioner/PreviewCardPositioner.tsx
packages/react/src/select/positioner/SelectPositioner.tsx
packages/react/src/tooltip/positioner/TooltipPositioner.tsx
packages/react/src/utils/constants.ts
packages/react/src/utils/useAnchorPositioning.ts

Adjustment to https://github.com/mui/base-ui/pull/1849. (`internal` tag as that PR can be used for release reference alone)
You don't want Select or Menu to flip to the right or left as a default if they don't fit on the top or bottom side, since they prefer to limit the height (`flip()` acts before `size()` does).
On the other hand, Popover, Tooltip, and Preview Card don't follow this and should flip the axis by default.
Also fixes `--transform-origin` calculation when `collisionAvoidance.side = 'shift'`: https://deploy-preview-1977--base-ui.netlify.app/experiments/popups/popups-transform-origin

[popups] Adjust `collisionAvoidance` defaults

---

docs/src/app/(public)/(content)/react/components/checkbox-group/demos/parent/css-modules/index.tsx

- [ ✅] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).
Noticed minor inconsistency with 🍎 naming when only 2/3 boxes were checked while pulling in the code from the snippet
Love the work you guys are doing!

[docs] checkbox group: granny smith apple naming consistency

---

packages/react/src/context-menu/index.parts.ts

🔴 ~`ItemIndicator`~ -> 🟢 `CheckboxItemIndicator`
Reported in https://discord.com/channels/1287292451308048406/1287292451308048409/1378046213001056316

[context menu] Fix CheckboxItemIndicator export

---

packages/react/src/menu/root/MenuRoot.tsx
packages/react/src/menu/trigger/MenuTrigger.test.tsx

Fixes #2039
The problem is the `useRole` hook checks `FloatingTree` by default, not the `MenuRootContext`, and since the Popover now has one, it adds the nested role incorrectly

[menu] Unset `role` from Trigger

---

packages/react/src/utils/store/useSelector.ts

Fix `useSyncExternalStore` import error in React 17. `use-sync-external-store/with-selector` does not import the shim, so it broke in React 17 which does not support `useSyncExternalStore`. The fix is to import `use-sync-external-store/shim/with-selector`.
This `use-sync-external-store/with-selector` import was added in [this commit](https://github.com/mui/base-ui/commit/5f03b929a5b1574fe3b860eca9de82ce22f61bcf#diff-44c136f3e29e44aa0beba0f06be73bbd87198d24961b506693f495755516ca06), so it isn't in any release yet.
[Error reproduction](https://codesandbox.io/p/sandbox/gracious-rosalind-chwync)
[Fix confirmation](https://codesandbox.io/p/devbox/heuristic-williams-r7lr9g?workspaceId=ws_PFkFFPimWAz2h3GBs6bbWx)
More info: https://github.com/mui/mui-x/issues/18303#issuecomment-2958392341

[core] Fix useSyncExternalStoreWithSelector in React 17

---

docs/src/app/(private)/experiments/menubar.tsx
packages/react/src/menu/trigger/MenuTrigger.tsx
packages/react/src/menubar/Menubar.test.tsx

Prevents closing the menu by emitting `'cancel-open'` when `allowMouseUpTriggerRef` is `false`
Fixes #2092

[menubar] Fix `closeOnClick: false` not working in nested menus

---

packages/react/src/select/positioner/SelectPositioner.tsx

The set-state-in-render pattern only works if the state is local to the component, otherwise it needs to use an effect now that it's in the store.
To reproduce the warning before, just open the select close to the edge of the viewport so it enters fallback mode

[select] Fix re-render warning in `Positioner` on fallback

---

docs/src/app/(private)/experiments/menu/complex-nesting.tsx
packages/react/src/alert-dialog/popup/AlertDialogPopup.tsx
packages/react/src/dialog/popup/DialogPopup.tsx
packages/react/src/dialog/popup/useDialogPopup.tsx
packages/react/src/dialog/root/DialogRoot.test.tsx

With #2042, merging with main I noticed two issues:
- `nativeButton={false}` must be specified on `Dialog.Trigger` since the `Menu.Item` is rendering it, which is not a native button (the keyboard handlers didn't work, only the pointer).  I wonder if this can be made more obvious/clear.
- The prop merging was incorrect in `useDialogPopup`, causing the `onKeyDown` handler to overwrite and break the handlers that handled the `Escape` event key bubbling

[dialog] Fix popup prop merging

---

packages/react/src/select/portal/SelectPortal.tsx
packages/react/src/select/root/SelectRoot.test.tsx
packages/react/src/select/root/SelectRoot.tsx
packages/react/src/select/root/useSelectRoot.ts
packages/react/src/select/store.ts
packages/react/src/select/trigger/useSelectTrigger.ts

From #2083. Since the items aren't rendered on mount anymore, they need to be force mounted when either:
1. `onChange` on the hidden input (for autofill handling) is invoked
2. The value changes externally (controlled mode) before the popup is opened to register the values/labels

[select] Fix programmatic value changes and autofill handling

---

docs/src/app/(public)/(content)/react/overview/accessibility/page.mdx

The URL changed. From https://github.com/Myndex/SAPC-APCA/tree/master, we can confirm that is new URL is correct.

[docs] Fix dead link to APCA

---

packages/react/src/dialog/close/DialogClose.test.tsx
packages/react/src/merge-props/mergeProps.test.ts
packages/react/src/merge-props/mergeProps.ts

`mergeProps` was handling event handlers incorrectly - when explicit `undefined` was passed, the merged result was `undefined` and other handlers were ignored.
For example, `<Dialog.Close onClick={undefined} />` would not close a Dialog.

[all-components] Do not overwrite event handler when `undefined` is passed explicitly

---

packages/react/src/collapsible/panel/useCollapsiblePanel.ts

Closes #2178
Both the strings are `''` in JSDOM, hence the warning

[collapsible][accordion] Fix test warning about mixed animation types

---

packages/react/src/select/item/SelectItem.tsx

From #2079, it this was incorrectly refactored to `!`

[select] Fix inverted flag in item mouseleave

---

docs/src/app/(public)/(content)/react/components/tooltip/page.mdx
docs/src/mdx-components.tsx

Current: https://base-ui.com/react/components/tooltip#accessibility-guidelines, rely on [Tight list](https://spec.commonmark.org/0.30/#tight)
[Loose list](https://spec.commonmark.org/0.30/#loose), without CSS changes
PR:
---
Context, I was looking at https://github.com/mui/base-ui/issues/559#issuecomment-2614736116, had some fun, same as https://github.com/mui/material-ui/pull/36190.

[docs] Use loose list when relevant

---

packages/react/src/number-field/input/NumberFieldInput.tsx
packages/react/src/number-field/root/NumberFieldRoot.test.tsx
packages/react/src/number-field/root/NumberFieldRoot.tsx
packages/react/src/select/root/SelectRoot.test.tsx
packages/react/src/select/root/SelectRoot.tsx
packages/react/src/select/root/useSelectRoot.ts
packages/react/src/select/utils/serialize.ts

Select was a regression from `beta.0`, likely due to the Store refactoring - the `store` value is updated later than the internal `value`, so the hidden `<input>` was getting a slightly stale value - the internal hook to commit the validation therefore was executing sooner than React had updated the hidden input `value` in the DOM for native validation
NumberField issue existed in `beta.0`
https://deploy-preview-2174--base-ui.netlify.app/experiments/form
1. Press submit without filling anything in
2. NumberField: Press increment -> validates immediately (required blur before)
3. Select: choose a value -> validates immediately (required blur before)

[select][number field] Fix revalidation on change

---

packages/react/src/floating-ui-react/components/FloatingFocusManager.tsx
packages/react/src/floating-ui-react/utils/nodes.test.ts
packages/react/src/floating-ui-react/utils/nodes.ts

The key is `isFocusInsideFloatingTree` needs to be true because sometimes the `activeElement` is one of the submenu items. However, the `isFocusInsideFloatingTree` check was faulty because `getNodeChildren` filters out closed children, but since they have an exit transition, they're closed-but-still-mounted (and the `activeElement` _can_ be inside them). In this case it shouldn't filter the open children so the `contains` check can work.
https://github.com/mui/base-ui/blob/11cbf2185d74ce5468263f31828cec0b68ad49c1/packages/react/src/floating-ui-react/components/FloatingFocusManager.tsx#L682-L684
On https://deploy-preview-2171--base-ui.netlify.app/experiments/menu/menu-fully-featured
Open root, navigate to the second nested submenu, press <kbd>Escape</kbd>. Try it several times since it …

[menu] Fix focus returning to root when submenus have exit transitions

---

packages/react/src/floating-ui-react/hooks/useListNavigation.ts

(Post-`beta.0` regression fix, so doesn't need to be mentioned in release)
Repro:
1. Open select with long scrollable list such that it enters fallback mode with `alignItemWithTrigger` still enabled
2. Scroll to last item, interact using keyboard
3. Close, re-open select, did not scroll the item into view
This _only_ happens with `alignItemWithTrigger` being in fallback mode, and only after interacting with the keyboard

[select] Fix scroll-item-into-view in fallback mode after keyboard interaction

---

packages/react/src/field/root/FieldRoot.test.tsx
packages/react/src/field/useField.ts
packages/react/src/form/Form.test.tsx

Fixes https://github.com/mui/base-ui/issues/2228

[field][form] Deregister fields from `Form` when unmounting

---

packages/react/src/composite/item/CompositeItem.tsx
packages/react/src/composite/item/useCompositeItem.ts
packages/react/src/composite/root/CompositeRoot.tsx
packages/react/src/menu/trigger/MenuTrigger.tsx
packages/react/src/menubar/Menubar.tsx
packages/react/src/navigation-menu/content/NavigationMenuContent.tsx
packages/react/src/navigation-menu/link/NavigationMenuLink.tsx
packages/react/src/navigation-menu/list/NavigationMenuList.tsx
packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx
packages/react/src/radio-group/RadioGroup.tsx
packages/react/src/radio/root/RadioRoot.tsx
packages/react/src/tabs/list/TabsList.tsx
packages/react/src/tabs/tab/TabsTab.tsx
packages/react/src/toggle-group/ToggleGroup.tsx
packages/react/src/toggle/Toggle.test.tsx
packages/react/src/toggle/Toggle.tsx
packages/react/src/toolbar/button/ToolbarButton.tsx
packages/react/src/toolbar/input/ToolbarInput.tsx
packages/react/src/toolbar/link/ToolbarLink.tsx
packages/react/src/toolbar/root/ToolbarRoot.tsx
packages/react/src/utils/constants.ts

Fixes #2255 by avoiding two `useRenderElement` passes

[composites] Avoid double `useRenderElement` passes

---

docs/reference/generated/navigation-menu-trigger.json
packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx

`NavigationMenu.Trigger` was missing `useButton` integration

[navigation menu] Add `useButton` integration to `Trigger`

---

packages/react/src/menu/trigger/MenuTrigger.tsx
packages/react/src/menubar/Menubar.test.tsx

`Menubar` `Menu.Trigger`s should have `role="menuitem"`.

[menubar] Fix triggers role

---

docs/reference/generated/number-field-root.json
packages/react/src/number-field/root/NumberFieldRoot.tsx

This likely existed for the initial implementation, before we made `Field`. It shouldn't be documented as a prop.

[number field] Remove `invalid` prop

---

packages/react/src/floating-ui-react/safePolygon.ts

Mentioned on Discord, some exotic runtimes (not Node.js/CF Workers) don't support `performance` and need a polyfill. It's not necessary to use here and can be replaced with `Date.now()`.

[safePolygon] Check for `performance` existence on server

---

packages/react/src/scroll-area/root/ScrollAreaRoot.tsx
packages/react/src/scroll-area/scrollbar/ScrollAreaScrollbar.tsx

Closes https://github.com/mui/base-ui/issues/2329
Doesn't seem to repro on macOS or Windows, so likely caused by some specific esoteric setup

[scroll area] Disable `user-select` on scrollbar and non-main button interactions

---

packages/react/src/toast/provider/ToastProvider.tsx
packages/react/src/toast/useToastManager.test.tsx

Fixes #2291
Takes into account the `timeout` option of the `success`/`error` states of `toastManager.promise()`

[toast] Fix `promise` method timeout option handling

---

packages/react/src/composite/composite.ts

Missed in https://github.com/mui/base-ui/pull/2332

[composite] Fix `scrollIntoViewIfNeeded` typo

---

docs/src/app/(public)/(content)/react/components/select/demos/hero/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/select/demos/hero/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/select/demos/multiple/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/select/demos/multiple/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/toast/demos/custom/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/toast/demos/hero/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/toast/demos/hero/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/toast/demos/position/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/toast/demos/position/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/toast/demos/promise/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/toast/demos/undo/css-modules/index.module.css

Containers or popups that are kept mounted in the DOM need to have `z-index` specified in order to appear above popups that are inserted later. e.g. `Toast.Viewport`, which is always in the DOM, should appear above `Dialog.Popup`.
`Select` and `Toast` are the two with implicit `keepMounted=true` behavior

[docs] Specify z-index on `keepMounted` popups/containers

---

docs/src/components/Subtitle/Subtitle.css

[docs] Fix Subtitle style

---

docs/src/app/(public)/(content)/react/components/menu/page.mdx

Menu.Backdrop is shown in the Anatomy but is not documented or exposed in the Menu API. This commit removes it from the Anatomy section to avoid confusion.

docs(menu): remove undocumented Menu.Backdrop from Anatomy section

---

packages/react/src/navigation-menu/trigger/NavigationMenuTrigger.tsx

Safari on iOS needs different ordering here for some reason after the changes in #2269

[navigation menu] Fix popup size transitions on iOS

---

docs/src/components/Header.tsx
docs/src/components/MobileNav.tsx

The mobile nav component needs to take into account external links (`.txt`)
Also the `href` prop was incorrectly forwarded to `<li>`

[docs] Fix llms.txt link on mobile

---

docs/src/app/(public)/(content)/react/components/radio/page.mdx

There was a typo in the form integration snippet for `Radio`.

[docs][radio group] Fix error in code snippet

---

scripts/releaseChangelog.mts

One step to execute https://www.notion.so/mui-org/Labeling-in-GitHub-1f1cbfe7b66081d8b18de652877d671e?source=copy_link#209cbfe7b660809b9528ff22dfa4c1f1.
I noticed this on #2434, I was about to add the "core" label until I realized we are renaming it in the organization. So I updated all the issues / PRs in this repository.

[support-infra] Rename label core to internal

---

docs/src/app/(private)/experiments/menu/menu-fully-featured.tsx
packages/react/src/floating-ui-react/hooks/useHover.ts
packages/react/src/menu/checkbox-item/MenuCheckboxItem.tsx
packages/react/src/menu/item/MenuItem.tsx
packages/react/src/menu/item/useMenuItem.ts
packages/react/src/menu/positioner/MenuPositioner.tsx
packages/react/src/menu/positioner/MenuPositionerContext.ts
packages/react/src/menu/radio-item/MenuRadioItem.tsx
packages/react/src/menu/root/MenuRoot.test.tsx
packages/react/src/menu/submenu-trigger/MenuSubmenuTrigger.tsx

Fixes a bunch edge-casey scenarios with submenus
1. Closing submenus across 3+ levels
- Hover third level nested submenu
- Hover root menu
- Now closes both submenus (previously, only the third would close)
2. Ensuring hover mouseleave is blocked when returning to the parent
- Hover third level nested submenu
- Hover its direct parent (second level)
- Hover out of the second level
- Now doesn't close (previously it would)
3. Ensuring submenus close when focusing a menu item in the parent
- Hover a submenu and onto a "non-focusable" section of text inside of it
- Hover out onto any menu item in the parent
- Now closes (previously it would stay stuck open until a different submenu opened)
https://deploy-preview-2483--base-ui.netlify.app/experiments/menu/menu-fully-featured

[menu] Fix submenu events

---

packages/react/package.json

https://unpkg.com/@base-ui-components/react@1.0.0-beta.2/package.json this is redundant; we never add this in the other public npm packages.

[internal] Remove implicit private: false in package.json

---

packages/utils/src/useControlled.test.tsx
packages/utils/src/useControlled.ts

Same as https://github.com/mui/material-ui/pull/46807.
*Since we are increasingly placing mui/base-ui at the core, I could have opened a PR here first (and propagated it in mui/material-ui), but I feel like there is a stronger test coverage in mui/material-ui ("stronger" = a large one, [3650 tests](https://app.circleci.com/pipelines/github/mui/base-ui/13134/workflows/1707fedf-411d-41b8-b252-d74318168640/jobs/133378) vs. [8253 tests](https://app.circleci.com/pipelines/github/mui/material-ui/159098/workflows/8cad5a20-3c67-4418-b80d-5dc9f89bf056/jobs/850554)), so I would rather test changes where the **hardest** constraints are first. However, we probably want to review them here first, and only after approve changes on mui/material-ui.*

[internal] Improve useControlled() strict mode handling

---

docs/src/app/(private)/experiments/forms/form.module.css
docs/src/app/(private)/experiments/slider/inset.mac.module.css
docs/src/app/(private)/experiments/slider/inset.native.module.css
docs/src/app/(private)/experiments/slider/slider.module.css
docs/src/app/(private)/experiments/slider/small.module.css
docs/src/app/(private)/experiments/slider/vertical.module.css
packages/react/src/slider/control/SliderControl.tsx
packages/react/src/slider/root/SliderRoot.test.tsx
packages/react/src/slider/root/SliderRoot.tsx
packages/react/src/slider/root/SliderRootContext.ts
packages/react/src/slider/thumb/SliderThumb.tsx

Single thumb: https://deploy-preview-2584--base-ui.netlify.app/react/components/slider
https://github.com/user-attachments/assets/70cff343-46da-4ffa-9ee3-afda8b0598a0
Multiple thumbs: https://deploy-preview-2584--base-ui.netlify.app/react/components/slider#range-slider
https://github.com/user-attachments/assets/82c8eed1-e124-46e9-bc38-95e42e518900
Differences from other libraries:
- Using the pointer (only) on the thumb doesn't trigger `:focus-visible` which is a bug in Radix https://github.com/radix-ui/primitives/issues/2397
- Using the pointer on a thumb that already shows `:focus-visible` without moving focus (e.g. starting a drag) does not cancel `:focus-visible`, there's a [web platform test](https://wpt.live/css/selectors/focus-visible-007.html) related to this. This is [different …

[slider] Fix thumb `:focus-visible` with mixed keyboard and pointer modality

---

docs/reference/generated/alert-dialog-popup.json
docs/reference/generated/dialog-popup.json
docs/reference/generated/menu-popup.json
docs/reference/generated/popover-popup.json
packages/react/src/alert-dialog/popup/AlertDialogPopup.test.tsx
packages/react/src/alert-dialog/popup/AlertDialogPopup.tsx
packages/react/src/dialog/popup/DialogPopup.test.tsx
packages/react/src/dialog/popup/DialogPopup.tsx
packages/react/src/floating-ui-react/components/FloatingFocusManager.test.tsx
packages/react/src/floating-ui-react/components/FloatingFocusManager.tsx
packages/react/src/menu/popup/MenuPopup.test.tsx
packages/react/src/menu/popup/MenuPopup.tsx
packages/react/src/popover/popup/PopoverPopup.test.tsx
packages/react/src/popover/popup/PopoverPopup.tsx
packages/react/test/floating-ui-tests/Menu.tsx
packages/react/test/floating-ui-tests/MenuOrientation.tsx
packages/react/test/floating-ui-tests/Navigation.tsx

Based on feedback from users, so `initialFocus={false|true}` and `initialFocus={() => false|true}`  are consistent.
Returning `null` in a function is the same as `true`, so that ref object or query selector nulls safely fall back to the default behavior.
> Marked internal since it's a post-PR refactor not yet in a release
Note - not necessarily a breaking change but should probably be mentioned: some users were using `initialFocus={-1}` to block initial focus even though it was an invalid type; now it's `initialFocus={false}` (closes #1679)

[popups] Use boolean values for fallback `initialFocus`/`finalFocus` behavior

---

packages/react/src/select/root/useSelectRoot.ts

This is a small tweak to #2523 to show the scroll arrows past the first or last item to include popup padding or labels. The initial visibility should use slightly different logic to the scroll arrow handlers.

[select] Fix scroll arrows visibility based on scroll amount

---

docs/src/app/(public)/(content)/react/components/alert-dialog/page.mdx
docs/src/app/(public)/(content)/react/components/dialog/page.mdx
docs/src/app/(public)/(content)/react/components/menu/page.mdx

Three snippets in the docs mention how to "manually" return focus to the menu trigger when closing a dialog that was open from a menu item. This is not required anymore since it's the default behavior. See https://codesandbox.io/p/sandbox/sharp-sky-jr38qg?file=/src/App.tsx
This PR removes `finalFocus` from the relevant snippets.

[docs] Remove unnecessary finalFocus

---

docs/src/app/(private)/experiments/menu/menu-horizontal.tsx
docs/src/app/(private)/experiments/menu/menu-nested.tsx
docs/src/app/(private)/experiments/popups/popups-in-popups.tsx

Found more invalid submenu usage that throws error.
Related: https://github.com/mui/base-ui/pull/2648

[docs] Migrate experiments to use `Menu.SubmenuRoot`

---

renovate.json

Do not auto-merge code infra PRs. These should be owned and merged by the code-infra team

[code-infra] Disable automerge for MUI devDependencies

---

packages/react/src/combobox/trigger/ComboboxTrigger.test.tsx
packages/react/src/combobox/trigger/ComboboxTrigger.tsx

This handler belongs in `onFocus` to mount the list for first typeahead, same as with Select.

[combobox] Fix initial closed typeahead

---

packages/react/src/collapsible/panel/CollapsiblePanel.tsx

This is a very minor PR to fix the type declaration. It current misses the `transitionStatus` field.

[collapsible] Fix CollapsiblePanel type to use its own state

---

docs/src/app/(public)/(content)/react/components/preview-card/page.mdx

The import path for `PreviewCard` is incorrect in the docs. This PR fixes it.

[docs] Fix incorrect component import in docs

---

packages/react/src/combobox/root/ComboboxRoot.test.tsx
packages/react/src/combobox/trigger/ComboboxTrigger.tsx

Prevents the input from taking focus when clicking the trigger to close. In Safari, the page can scroll to the bottom when toggling with the trigger.

[combobox] Fix input focus on close when clicking trigger

---

packages/react/src/dialog/close/useDialogClose.ts
packages/react/src/use-button/useButton.test.tsx
packages/react/src/use-button/useButton.ts

As put in the title, this PR updates `useButton` hook to update `disabled` property also when element itself changes. Without this, it becomes disabled when ref changes and `focusableWhenDisabled` stops working properly.
Ref can change especially when using `render` prop and custom components: https://codesandbox.io/p/sandbox/2756-l3j4xk
To solve it, this PR updates `buttonRef` to a callback and update the option manually. We can use `useState` as the ref, but it forces re-render which I think is not necessary at the moment.

[useButton] Update disabled prop of the button when ref changes

---

packages/react/src/slider/root/SliderRoot.test.tsx
packages/react/src/slider/root/SliderRoot.tsx
packages/react/src/slider/root/SliderRootContext.ts
packages/react/src/slider/thumb/SliderThumb.tsx

Fixes:
- `aria-valuemin` and `aria-valuemax` aren't needed on `input type="range"`: https://w3c.github.io/html-aria/#att-max
- `name` attribute should not fall back to an empty string
From https://github.com/mui/base-ui/pull/2718#issue-3403364165

[slider] Fix input attributes

---

packages/react/src/scroll-area/viewport/ScrollAreaViewport.tsx

This is mainly visible in Safari with inset scrollbars due to the updates happening in a microtask.

[scroll area] Fix thumb size flicker

---

packages/react/src/number-field/scrub-area/NumberFieldScrubArea.test.tsx

I saw this from #2726 (was added before this PR). I believe the current test best practice we use is to try to rely on synchronous tests anytime it's possible because 1. our users are doing the same (so we experience issues ourselves) 2. It's simpler (so we move with less weight). A quick clean-up.

[internal] Remove unnecessary await waitFor

---

docs/src/mdx-components.tsx

A small one. Each component adds about 10% of rendering slowness overhead.
Preview: https://deploy-preview-2781--base-ui.netlify.app/react/overview/quick-start

[docs-infra] Flatten MDX link component

---

docs/reference/generated/navigation-menu-link.json
packages/react/src/navigation-menu/link/NavigationMenuLink.test.tsx
packages/react/src/navigation-menu/link/NavigationMenuLink.tsx

This needs to be configurable for a couple of reasons:
1. External links shouldn't close the menu, only client-side ones. Stripe and Apple leave theirs open as they act as external links.
2. Nested menus shouldn't close their menu since they're meant to be always-open
This API matches regular `Menu` but `false` by default

[navigation menu] Make link close on click configurable

---

packages/react/src/collapsible/panel/useCollapsiblePanel.ts

The change to respect the `display` property has some quirks. If `justify-content: end` is being used (which is necessary so that the `border-radius` of the bottom edge doesn't get clipped while transitioning), the `.scrollHeight` is `0` initially. We need to manually unset the `justify-content`/`align-items` values. 
Also the computed styles object is "live" so it should be recalculated on every access. It was empty `""` after the first open.

[collapsible] Fix opening transition regression

---

packages/react/src/autocomplete/item/AutocompleteItem.test.tsx
packages/react/src/combobox/input/ComboboxInput.tsx
packages/react/src/combobox/item/ComboboxItem.test.tsx
packages/react/src/combobox/list/ComboboxList.tsx
packages/react/src/combobox/root/ComboboxRootInternal.tsx
packages/react/src/combobox/store.ts

Undoes the breaking change from https://github.com/mui/base-ui/pull/2682 (marked internal since it was a post-release change)
Pressing <kbd>Enter</kbd> on `Input` or `List` should continue to fire `onClick` on `Item`, since the logic may be entirely contained in there (particularly for command palette patterns, or anything that avoids a surrounding `form`)
This change also ensures the correct event is still passed as part of `eventDetails`, unlike before

[combobox][autocomplete] Restore item `onClick` on keypress

---

test/setupVitest.ts

As chai was updated in code-infra packages, it no longer exports a default value.
Surprisingly, tests were still working on CI, but failing for me locally.

[internal] Do not use default import from chai

---

packages/react/src/combobox/root/ComboboxRoot.test.tsx
packages/react/src/combobox/root/ComboboxRootInternal.tsx

`item-press` could be emitted in this input value restoration case (e.g. select value, type something, press <kbd>Esc</kbd>) which is misleading as it isn't linked with item clicks.

[combobox] Fix misleading `item-press` reason in `onInputValueChange`

---

docs/src/app/(public)/(content)/react/components/scroll-area/demos/hero/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/scroll-area/demos/hero/tailwind/index.tsx
docs/src/components/ScrollArea.css

Fixes #2825
This prevents pointer interactions from taking effect unless you start scrolling on touch, at which point you can grab the thumb like on iOS.
Preview: https://deploy-preview-2827--base-ui.netlify.app/react/components/scroll-area

[docs][scroll area] Fix hijacking scroll when using touch

---

packages/utils/src/store/ReactStore.ts

Moved the initialization of uncontrolled values to the render phase, so they are immediately available, similarly to how the `useControlled` hook works.

[utils] useControlledProp: initialize uncontrolled value as soon as possible

---

packages/react/src/combobox/input/ComboboxInput.test.tsx
packages/react/src/combobox/input/ComboboxInput.tsx
packages/react/src/combobox/root/ComboboxRoot.test.tsx

Retaining the value in a single-select combobox when clearing the input is somewhat unexpected behavior
Preview: https://deploy-preview-2860--base-ui.netlify.app/react/components/combobox

[combobox] Clear single value on input clear

---

docs/src/app/(public)/(content)/react/components/combobox/demos/input-inside-popup/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/combobox/demos/input-inside-popup/tailwind/index.tsx

This is a really minor, but weird, issue in the docs style for the `input-inside-popup` demo.
Even if there was enough space on the bottom to position the popup there, it would choose to flip to the top if there was **more** space there. Kind of like `autoPlacement()` in Floating UI instead of `flip()` (even though it's not being used.)
`var(--available-height)` is already handled by `List`, so there aren't any visual changes.
With the fix, it correctly chooses the bottom if it can. Previously it was choose the top (shown with the arrow) in this particular scenario. The viewport height and scroll position need to be specific enough for the issue to be reproduced.

[docs][combobox] Fix popup height style for inside-popup demo

---

docs/src/app/(public)/(content)/react/components/alert-dialog/demos/hero/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/alert-dialog/demos/hero/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/combobox/demos/creatable/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/combobox/demos/creatable/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/dialog/demos/close-confirmation/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/dialog/demos/close-confirmation/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/dialog/demos/hero/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/dialog/demos/hero/tailwind/index.tsx
docs/src/app/(public)/(content)/react/components/dialog/demos/nested/css-modules/index.module.css
docs/src/app/(public)/(content)/react/components/dialog/demos/nested/tailwind/index.tsx
docs/src/app/(public)/(content)/react/overview/quick-start/page.mdx
docs/src/app/(public)/layout.css
docs/src/components/MobileNav.css

Third attempt at fixing this...
This one instead only targets iOS Safari. Caveat: if other mobile browsers start allowing content to be seen beneath the viewport, it'll fail for them. 
To avoid the caveat, we'd need to target the `data-base-ui-scroll-locked` attr placed on the `<html>` tag, which is **only** applied if there are inset scrollbars. The scroll lock for inset scrollbars is special and breaks `position: absolute` backdrops because it sets a fixed height on the body.
This one avoids breaking the inset scrollbar scroll lock, while allowing non-iOS mobile browser UIs to also work if they change. Presumably, browsers with inset scrollbars will never face this issue given it's a mobile/overlay-scrollbar type of UI paradigm 
```css
.Backdrop {
position: absolute;
min-height: 100dvh; …
```

[docs] Fix iOS 26+ backdrops

---

.github/workflows/publish.yml
docs/package.json
package.json
pnpm-lock.yaml
scripts/README.md

* Allow publishing to different dist tag than "latest"
* Tweak docs deploy to fetch latest master first, like https://github.com/mui/material-ui/pull/47018

[code-infra] Support custom npm dist tags during release

---

packages/react/src/combobox/root/AriaCombobox.tsx
packages/react/src/combobox/root/ComboboxRoot.test.tsx
packages/react/src/select/root/SelectRoot.test.tsx
packages/react/src/select/root/SelectRoot.tsx

Since `multiple` modes on each use separate hidden inputs, the main hidden input needs to remove `required` when a value exists
Fixes #2913 (https://codesandbox.io/p/sandbox/ecstatic-fire-nzxvy9)

[select][combobox] Fix required form submission with multiple values

---

packages/react/src/combobox/input/ComboboxInput.test.tsx
packages/react/src/combobox/input/ComboboxInput.tsx

Firefox automatically scrolls an overflowing input, but Chrome/Safari do not 
Fixes #2882
https://codesandbox.io/p/sandbox/heuristic-platform-8r3n93

[combobox][autocomplete] Fix `Home`/`End` Input scroll in Chrome/Safari
